export interface MockAssessmentRecord {
  id: string
  orderId: string
  studentId: string
  studentName: string
  studentAccount?: string
  subject: string
  grade: string
  assessmentType: "phase" | "entry" | "mock"
  conclusion: "breakthrough" | "improved" | "no_progress" | "declined" | "risk"
  currentScore?: string
  previousScore?: string
  problems?: string[]
  description?: string
  assessedAt: Date
  teacherId: string
  teacherName: string
  managerId?: string
  managerName: string
  createdAt: Date
}

export const mockAssessments: MockAssessmentRecord[] = [
  {
    id: "asm-1",
    orderId: "ord-2",
    studentId: "stu-1",
    studentName: "陈小明",
    studentAccount: "G20240301",
    subject: "数学",
    grade: "四年级",
    assessmentType: "phase",
    conclusion: "improved",
    currentScore: "85",
    previousScore: "72",
    problems: ["calculation", "careless"],
    description: "本次阶段测成绩提升明显，计算准确率有进步，但仍有粗心丢分的情况。",
    assessedAt: new Date("2024-03-02T19:00:00"),
    teacherId: "user-tutor-1",
    teacherName: "李伴学",
    managerId: "user-manager-1",
    managerName: "王学管",
    createdAt: new Date("2024-03-02T20:00:00"),
  },
  {
    id: "asm-2",
    orderId: "ord-8",
    studentId: "stu-2",
    studentName: "李小华",
    studentAccount: "G20240215",
    subject: "数学",
    grade: "初二",
    assessmentType: "phase",
    conclusion: "breakthrough",
    currentScore: "96",
    previousScore: "78",
    problems: [],
    description: "本次测评取得关键突破，代数与几何模块均有显著进步。",
    assessedAt: new Date("2024-03-10T16:00:00"),
    teacherId: "user-tutor-2",
    teacherName: "王金牌",
    managerId: "user-manager-1",
    managerName: "王学管",
    createdAt: new Date("2024-03-10T16:40:00"),
  },
  {
    id: "asm-3",
    orderId: "ord-9",
    studentId: "stu-4",
    studentName: "张小丽",
    studentAccount: "G20240112",
    subject: "化学",
    grade: "高一",
    assessmentType: "entry",
    conclusion: "no_progress",
    currentScore: "65",
    previousScore: "67",
    problems: ["basic", "method"],
    description: "入学测评显示基础薄弱，需从基本概念入手加强训练。",
    assessedAt: new Date("2024-03-15T18:30:00"),
    teacherId: "user-tutor-3",
    teacherName: "刘资深",
    managerId: "user-manager-1",
    managerName: "王学管",
    createdAt: new Date("2024-03-15T19:10:00"),
  },
  {
    id: "asm-4",
    orderId: "ord-extra-3",
    studentId: "stu-3",
    studentName: "王小红",
    studentAccount: "G20240105",
    subject: "化学",
    grade: "高一",
    assessmentType: "mock",
    conclusion: "risk",
    currentScore: "42",
    previousScore: "58",
    problems: ["basic", "reading", "method"],
    description: "模拟考成绩下降明显，审题能力和基础知识均需重点关注。",
    assessedAt: new Date("2024-03-20T20:00:00"),
    teacherId: "user-tutor-1",
    teacherName: "李伴学",
    managerId: "user-manager-1",
    managerName: "王学管",
    createdAt: new Date("2024-03-20T20:35:00"),
  },
  {
    id: "asm-5",
    orderId: "rfd-regular-100-c99",
    studentId: "stu-pay-07",
    studentName: "高三学生A",
    studentAccount: "G20250901",
    subject: "化学",
    grade: "高三",
    assessmentType: "phase",
    conclusion: "improved",
    currentScore: "88",
    previousScore: "79",
    problems: ["careless"],
    description: "阶段测成绩稳步提升，粗心问题有所改善但仍需注意。",
    assessedAt: new Date("2025-09-05T14:00:00"),
    teacherId: "user-tutor-7",
    teacherName: "赵老师",
    managerId: "user-manager-2",
    managerName: "李学管",
    createdAt: new Date("2025-09-05T14:30:00"),
  },
  {
    id: "asm-6",
    orderId: "rfd-red-junior",
    studentId: "stu-pay-09",
    studentName: "初二学生B",
    studentAccount: "G20250820",
    subject: "数学",
    grade: "初二",
    assessmentType: "entry",
    conclusion: "breakthrough",
    currentScore: "92",
    previousScore: "71",
    problems: [],
    description: "入学测表现出色，基础扎实，后续可提升难题攻关能力。",
    assessedAt: new Date("2025-09-03T15:00:00"),
    teacherId: "user-tutor-8",
    teacherName: "周老师",
    managerId: "user-manager-2",
    managerName: "李学管",
    createdAt: new Date("2025-09-03T15:45:00"),
  },
  {
    id: "asm-7",
    orderId: "rfd-red-high",
    studentId: "stu-pay-10",
    studentName: "高二学生C",
    studentAccount: "G20250818",
    subject: "英语",
    grade: "高二",
    assessmentType: "phase",
    conclusion: "no_progress",
    currentScore: "70",
    previousScore: "72",
    problems: ["reading"],
    description: "阶段测变化不大，阅读理解仍为主要失分点。",
    assessedAt: new Date("2025-09-04T19:00:00"),
    teacherId: "user-tutor-9",
    teacherName: "吴老师",
    managerId: "user-manager-2",
    managerName: "李学管",
    createdAt: new Date("2025-09-04T19:20:00"),
  },
  {
    id: "asm-8",
    orderId: "ord-sales3-4",
    studentId: "stu-5",
    studentName: "赵小强",
    studentAccount: "G20250722",
    subject: "英语",
    grade: "高三",
    assessmentType: "mock",
    conclusion: "declined",
    currentScore: "68",
    previousScore: "82",
    problems: ["method", "careless"],
    description: "模拟考成绩下滑，需复盘答题策略与时间分配。",
    assessedAt: new Date("2025-08-01T17:30:00"),
    teacherId: "user-tutor-15",
    teacherName: "郭老师",
    managerId: "user-manager-3",
    managerName: "张学管",
    createdAt: new Date("2025-08-01T17:55:00"),
  },
]
