import { CourseTransfer, TransferType, TransferStatus } from '@/types'

export const mockCourseTransfers: CourseTransfer[] = [
  {
    id: 'ct-demo-1',
    type: TransferType.GRADE_UPGRADE,
    sourceOrderId: 'ord-sales1-4',
    sourceStudentId: 'stu-4',
    sourceStudentName: '赵六',
    sourceSubject: '化学',
    sourceGrade: '高二',
    sourceUnitPrice: 300,
    sourceNetUnitPrice: 280,
    sourceTransferredHours: 30,
    sourceRemainingBefore: 30,
    targetOrderId: 'ord-extra-4',
    targetStudentId: 'stu-4',
    targetStudentName: '赵六',
    targetSubject: '化学',
    targetGrade: '高三',
    targetUnitPrice: 320,
    targetNetUnitPrice: 300,
    targetReceivedHours: 28,
    sourceValue: 8400,
    targetValue: 8400,
    priceDifference: 0,
    status: TransferStatus.APPROVED,
    remarks: '高二升高三，课时标准升级',
    dingbanxueReminderStatus: 'CONFIRMED',
    createdBy: 'user-operator-1',
    createdByName: '运营专员',
    firstReviewNote: '信息核实无误',
    firstReviewerId: 'user-operator-1',
    firstReviewerName: '财务专员',
    firstReviewedAt: new Date('2025-06-01T10:30:00'),
    secondReviewNote: '已确认鼎伴学课时转移完成',
    secondReviewerId: 'user-operator-1',
    secondReviewerName: '财务主管',
    secondReviewedAt: new Date('2025-06-01T11:00:00'),
    createdAt: new Date('2025-06-01T10:00:00'),
    updatedAt: new Date('2025-06-01T11:00:00'),
  },
  {
    id: 'ct-demo-2',
    type: TransferType.CROSS_STUDENT,
    sourceOrderId: 'ord-sales2-5',
    sourceStudentId: 'stu-5',
    sourceStudentName: '孙七',
    sourceSubject: '化学',
    sourceGrade: '初三',
    sourceUnitPrice: 250,
    sourceNetUnitPrice: 230,
    sourceTransferredHours: 20,
    sourceRemainingBefore: 55,
    targetOrderId: 'ord-sales3-1',
    targetStudentId: 'stu-2',
    targetStudentName: '李四',
    targetSubject: '数学',
    targetGrade: '高二',
    targetUnitPrice: 300,
    targetNetUnitPrice: 280,
    targetReceivedHours: 16.5,
    sourceValue: 4600,
    targetValue: 4620,
    priceDifference: -20,
    status: TransferStatus.PENDING_SECOND_REVIEW,
    remarks: '校长要求：孙七化学课部分转给李四数学',
    dingbanxueReminderStatus: 'PENDING',
    createdBy: 'user-operator-1',
    createdByName: '运营专员',
    firstReviewNote: '一审通过',
    firstReviewerId: 'user-operator-1',
    firstReviewerName: '财务专员',
    firstReviewedAt: new Date('2025-06-05T14:30:00'),
    createdAt: new Date('2025-06-05T14:00:00'),
    updatedAt: new Date('2025-06-05T14:30:00'),
  },
  {
    id: 'ct-demo-3',
    type: TransferType.GRADE_UPGRADE,
    sourceOrderId: 'ord-sales2-6',
    sourceStudentId: 'stu-1',
    sourceStudentName: '张三',
    sourceSubject: '数学',
    sourceGrade: '五年级',
    sourceUnitPrice: 150,
    sourceNetUnitPrice: 130,
    sourceTransferredHours: 22,
    sourceRemainingBefore: 22,
    targetOrderId: 'ord-reserved-demo',
    targetStudentId: 'stu-1',
    targetStudentName: '张三',
    targetSubject: '数学',
    targetGrade: '六年级',
    targetUnitPrice: 180,
    targetNetUnitPrice: 160,
    targetReceivedHours: 17.5,
    sourceValue: 2860,
    targetValue: 2800,
    priceDifference: 60,
    status: TransferStatus.PENDING_FIRST_REVIEW,
    supplementaryVouchers: [
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
    ],
    remarks: '五年级升六年级，待财务审核',
    dingbanxueReminderStatus: 'PENDING',
    createdBy: 'user-operator-1',
    createdByName: '运营专员',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
]
