import { LessonFeedbackRecord } from '@/types'

export const mockFeedbacks: LessonFeedbackRecord[] = [
  {
    id: 'fb-1',
    orderId: 'ord-2',
    studentId: 'stu-1',
    teacherId: 'user-tutor-1',
    date: '2023-09-08',
    startTime: '20:00',
    endTime: '21:00',
    deductHours: '1',
    content: '复习了分式的基本概念和运算性质，重点讲解了分式通分的方法。',
    methods: '通分时先找最简公分母',
    mistakes: '注意符号变化时的变号问题',
    performance: '听课认真，互动积极',
    homework: '完成课后练习题1-5',
    parentFeedback: {
      rating: 5,
      tags: ['🧘 无明显问题'],
      evaluation: {
        knowledge_absorption: '很好',
        student_explain: '有',
        professionalism: '专业严谨',
        responsibility: '主动关注',
        patience: '非常耐心',
        post_feedback: '及时详细',
        punctuality: '很守时',
        camera: '开',
        network: '网络通畅',
        environment: '安静',
      },
      remarks: '老师讲得很细致，孩子听懂了',
      submittedAt: new Date('2023-09-09T08:30:00')
    },
    createdAt: new Date('2023-09-08T21:10:00'),
    updatedAt: new Date('2023-09-08T21:10:00')
  },
  {
    id: 'fb-2',
    orderId: 'ord-2',
    studentId: 'stu-1',
    teacherId: 'user-tutor-1',
    date: '2023-09-10',
    startTime: '10:00',
    endTime: '12:00',
    deductHours: '2',
    content: '讲解了分式方程的解法，包括去分母、验根等步骤。',
    methods: '去分母时各项都要乘',
    mistakes: '忘记验根导致增根未排除',
    performance: '计算能力有待提高，但思路清晰',
    homework: '订正错题，预习下一章',
    createdAt: new Date('2023-09-10T12:15:00'),
    updatedAt: new Date('2023-09-10T12:15:00')
  },
  {
    id: 'fb-3',
    orderId: 'ord-2',
    studentId: 'stu-1',
    teacherId: 'user-tutor-1',
    date: '2023-09-15',
    startTime: '19:00',
    endTime: '20:00',
    deductHours: '1',
    content: '针对近期作业中的错题进行了集中讲解，分析了错误原因。',
    methods: '错题整理与归纳',
    mistakes: '审题不清，计算粗心',
    performance: '能够主动反思错误，态度端正',
    homework: '整理错题本，完成针对性练习',
    createdAt: new Date('2023-09-15T20:10:00'),
    updatedAt: new Date('2023-09-15T20:10:00')
  },
  {
    id: 'fb-4',
    orderId: 'ord-2',
    studentId: 'stu-1',
    teacherId: 'user-tutor-1',
    date: '2023-09-20',
    startTime: '20:00',
    endTime: '21:00',
    deductHours: '1',
    content: '学习了反比例函数的图像与性质。',
    methods: '描点法画图',
    mistakes: 'k值正负对图像象限的影响混淆',
    performance: '新知识接受较快，但在绘图细节上需要加强',
    homework: '完成练习册第3章第2节',
    parentFeedback: {
      rating: 3,
      tags: ['🤔 讲解不够清楚', '😵 节奏偏快 / 偏慢'],
      evaluation: {
        knowledge_absorption: '一般',
        student_explain: '无',
        professionalism: '基本专业',
        responsibility: '主动关注',
        patience: '一般耐心',
        post_feedback: '简单概括',
        punctuality: '很守时',
        camera: '开',
        network: '网络通畅',
        environment: '安静',
      },
      remarks: '孩子说今天讲得有点快，有些地方没太听懂',
      submittedAt: new Date('2023-09-21T09:00:00')
    },
    createdAt: new Date('2023-09-20T21:05:00'),
    updatedAt: new Date('2023-09-20T21:05:00')
  },
  {
    id: 'fb-6',
    orderId: 'ord-2',
    studentId: 'stu-1',
    teacherId: 'user-tutor-1',
    date: '2023-09-25',
    startTime: '20:00',
    endTime: '20:30',
    deductHours: '0.5',
    content: '考前答疑，快速梳理了本章重点公式。',
    performance: '状态不错，信心较足',
    createdAt: new Date('2023-09-25T20:35:00'),
    updatedAt: new Date('2023-09-25T20:35:00')
  },
  // Order 4 (Student: 王小红) Feedbacks
  {
    id: 'fb-5',
    orderId: 'ord-4',
    studentId: 'stu-3',
    teacherId: 'user-tutor-1',
    date: '2023-11-28',
    startTime: '16:30',
    endTime: '18:30',
    deductHours: '2',
    content: '阅读理解专项训练，重点讲解了说明文的阅读技巧。',
    methods: '寻找中心句，理清说明顺序',
    mistakes: '概括文章大意时语言不精炼',
    performance: '阅读速度有提升，但在精准度上还需磨练',
    homework: '完成两篇说明文阅读理解',
    createdAt: new Date('2023-11-28T18:40:00'),
    updatedAt: new Date('2023-11-28T18:40:00')
  },
  {
    id: 'fb-4-1',
    orderId: 'ord-4',
    studentId: 'stu-3',
    teacherId: 'user-tutor-1',
    date: '2023-12-01',
    startTime: '16:30',
    endTime: '18:30',
    deductHours: '2',
    content: '记叙文写作指导，练习了如何进行细节描写。',
    methods: '五感法描写',
    mistakes: '流水账，缺乏重点',
    performance: '写作兴趣浓厚，但结构安排还需加强',
    homework: '修改课堂作文《难忘的一天》',
    parentFeedback: {
      rating: 5,
      tags: ['🧘 无明显问题'],
      evaluation: {
        knowledge_absorption: '很好',
        student_explain: '有',
        professionalism: '专业严谨',
        responsibility: '主动关注',
        patience: '非常耐心',
        post_feedback: '及时详细',
        punctuality: '很守时',
        camera: '开',
        network: '网络通畅',
        environment: '安静',
      },
      remarks: '孩子回家说今天学到了很多写作技巧，很开心',
      submittedAt: new Date('2023-12-02T10:00:00')
    },
    createdAt: new Date('2023-12-01T19:00:00'),
    updatedAt: new Date('2023-12-01T19:00:00')
  },
  {
    id: 'fb-4-2',
    orderId: 'ord-4',
    studentId: 'stu-3',
    teacherId: 'user-tutor-1',
    date: '2023-12-08',
    startTime: '16:30',
    endTime: '18:30',
    deductHours: '2',
    content: '古诗词鉴赏，讲解了唐诗的常见意象和情感表达。',
    methods: '知人论世',
    mistakes: '对典故不熟悉',
    performance: '背诵流畅，但在理解深层含义上有困难',
    homework: '背诵并默写《琵琶行》选段',
    parentFeedback: {
      rating: 4,
      tags: ['🤔 讲解不够清楚'],
      evaluation: {
        knowledge_absorption: '较好',
        student_explain: '无',
        professionalism: '专业严谨',
        responsibility: '主动关注',
        patience: '非常耐心',
        post_feedback: '及时详细',
        punctuality: '很守时',
        camera: '开',
        network: '网络通畅',
        environment: '安静',
      },
      remarks: '古诗词部分孩子觉得有点难，希望能多举些例子',
      submittedAt: new Date('2023-12-09T09:30:00')
    },
    createdAt: new Date('2023-12-08T18:50:00'),
    updatedAt: new Date('2023-12-08T18:50:00')
  },
  {
    id: 'fb-4-3',
    orderId: 'ord-4',
    studentId: 'stu-3',
    teacherId: 'user-tutor-1',
    date: '2023-12-15',
    startTime: '16:30',
    endTime: '18:30',
    deductHours: '2',
    content: '期末复习第一讲：基础知识巩固，包括字音字形、成语运用。',
    methods: '归纳记忆法',
    mistakes: '形近字混淆',
    performance: '基础比较扎实，但在易错字上还需留心',
    homework: '完成基础知识专项卷',
    createdAt: new Date('2023-12-15T18:45:00'),
    updatedAt: new Date('2023-12-15T18:45:00')
  },
  {
    id: 'fb-4-4',
    orderId: 'ord-4',
    studentId: 'stu-3',
    teacherId: 'user-tutor-1',
    date: '2023-11-10',
    startTime: '16:30',
    endTime: '18:30',
    deductHours: '2',
    content: '文言文阅读入门，学习了常用的实词和虚词。',
    methods: '组词法推断词义',
    mistakes: '古今异义词理解错误',
    performance: '对文言文有畏难情绪，需要多鼓励',
    homework: '翻译《伤仲永》',
    parentFeedback: {
      rating: 5,
      tags: ['🧘 无明显问题'],
      evaluation: {
        knowledge_absorption: '较好',
        student_explain: '有',
        professionalism: '专业严谨',
        responsibility: '主动关注',
        patience: '非常耐心',
        post_feedback: '及时详细',
        punctuality: '很守时',
        camera: '开',
        network: '网络通畅',
        environment: '安静',
      },
      submittedAt: new Date('2023-11-11T11:00:00')
    },
    createdAt: new Date('2023-11-10T18:40:00'),
    updatedAt: new Date('2023-11-10T18:40:00')
  },
  {
    id: 'fb-4-5',
    orderId: 'ord-4',
    studentId: 'stu-3',
    teacherId: 'user-tutor-1',
    date: '2024-01-05',
    startTime: '16:30',
    endTime: '18:30',
    deductHours: '2',
    content: '期末模拟考试试卷讲评，重点分析了作文失分点。',
    methods: '审题立意三步走',
    mistakes: '作文偏题',
    performance: '考后心态平和，能虚心接受建议',
    homework: '重写期末模拟作文',
    createdAt: new Date('2024-01-05T19:00:00'),
    updatedAt: new Date('2024-01-05T19:00:00')
  },
  // 额外反馈数据用于分页测试
  {
    id: 'fb-extra-1',
    orderId: 'ord-extra-1',
    studentId: 'stu-1',
    teacherId: 'user-tutor-1',
    date: '2024-01-16',
    startTime: '19:00',
    endTime: '20:30',
    deductHours: '1.5',
    content: '英语阅读理解专项训练，讲解了记叙文和说明文的阅读技巧。',
    methods: '抓住关键词，理解文章主旨',
    mistakes: '细节题容易遗漏信息',
    performance: '阅读速度有明显提升',
    homework: '完成3篇阅读理解练习',
    parentFeedback: {
      rating: 5,
      tags: ['🧘 无明显问题'],
      evaluation: {
        knowledge_absorption: '很好',
        student_explain: '有',
        professionalism: '专业严谨',
        responsibility: '主动关注',
        patience: '非常耐心',
        post_feedback: '及时详细',
        punctuality: '很守时',
        camera: '开',
        network: '网络通畅',
        environment: '安静',
      },
      remarks: '孩子说阅读理解学到了很多方法',
      submittedAt: new Date('2024-01-17T08:00:00')
    },
    createdAt: new Date('2024-01-16T20:40:00'),
    updatedAt: new Date('2024-01-16T20:40:00')
  },
  {
    id: 'fb-extra-2',
    orderId: 'ord-extra-2',
    studentId: 'stu-2',
    teacherId: 'user-tutor-1',
    date: '2024-01-19',
    startTime: '18:00',
    endTime: '20:00',
    deductHours: '2',
    content: '电学基础知识复习，重点讲解了欧姆定律的应用。',
    methods: '电路图分析法',
    mistakes: '串并联电路判断有误',
    performance: '认真听讲，但需要多做练习巩固',
    homework: '完成电学综合题10道',
    createdAt: new Date('2024-01-19T20:10:00'),
    updatedAt: new Date('2024-01-19T20:10:00')
  },
  {
    id: 'fb-extra-3',
    orderId: 'ord-extra-3',
    studentId: 'stu-3',
    teacherId: 'user-tutor-1',
    date: '2024-01-21',
    startTime: '20:00',
    endTime: '21:30',
    deductHours: '1.5',
    content: '化学方程式配平专题，讲解了常见的配平方法。',
    methods: '观察法、奇偶法',
    mistakes: '化学式书写不规范',
    performance: '学习态度端正，进步明显',
    homework: '配平练习30题',
    parentFeedback: {
      rating: 4,
      tags: ['🧘 无明显问题'],
      evaluation: {
        knowledge_absorption: '较好',
        student_explain: '无',
        professionalism: '专业严谨',
        responsibility: '主动关注',
        patience: '非常耐心',
        post_feedback: '及时详细',
        punctuality: '很守时',
        camera: '开',
        network: '网络通畅',
        environment: '安静',
      },
      submittedAt: new Date('2024-01-22T09:00:00')
    },
    createdAt: new Date('2024-01-21T21:40:00'),
    updatedAt: new Date('2024-01-21T21:40:00')
  },
  {
    id: 'fb-extra-4',
    orderId: 'ord-extra-4',
    studentId: 'stu-4',
    teacherId: 'user-tutor-1',
    date: '2024-01-23',
    startTime: '14:00',
    endTime: '16:00',
    deductHours: '2',
    content: '细胞结构与功能复习，重点讲解了线粒体和叶绿体的区别。',
    methods: '对比记忆法',
    mistakes: '细胞器功能混淆',
    performance: '理解能力强，但记忆需要加强',
    homework: '整理细胞器对比表',
    createdAt: new Date('2024-01-23T16:15:00'),
    updatedAt: new Date('2024-01-23T16:15:00')
  },
  {
    id: 'fb-extra-5',
    orderId: 'ord-extra-5',
    studentId: 'stu-5',
    teacherId: 'user-tutor-1',
    date: '2024-01-26',
    startTime: '10:00',
    endTime: '12:00',
    deductHours: '2',
    content: '中国古代史专题复习，讲解了隋唐时期的重大历史事件。',
    methods: '时间轴记忆法',
    mistakes: '历史事件时间顺序记混',
    performance: '对历史很感兴趣，记忆力不错',
    homework: '整理隋唐大事年表',
    parentFeedback: {
      rating: 5,
      tags: ['🧘 无明显问题'],
      evaluation: {
        knowledge_absorption: '很好',
        student_explain: '有',
        professionalism: '专业严谨',
        responsibility: '主动关注',
        patience: '非常耐心',
        post_feedback: '及时详细',
        punctuality: '很守时',
        camera: '开',
        network: '网络通畅',
        environment: '安静',
      },
      remarks: '孩子很喜欢历史课',
      submittedAt: new Date('2024-01-27T10:00:00')
    },
    createdAt: new Date('2024-01-26T12:10:00'),
    updatedAt: new Date('2024-01-26T12:10:00')
  },
  {
    id: 'fb-extra-6',
    orderId: 'ord-extra-6',
    studentId: 'stu-1',
    teacherId: 'user-tutor-1',
    date: '2024-01-29',
    startTime: '19:00',
    endTime: '20:30',
    deductHours: '1.5',
    content: '世界地理专题，讲解了气候类型及其分布。',
    methods: '地图记忆法',
    mistakes: '气候特征描述不准确',
    performance: '空间想象能力较好',
    homework: '绘制世界气候分布图',
    createdAt: new Date('2024-01-29T20:40:00'),
    updatedAt: new Date('2024-01-29T20:40:00')
  },
  {
    id: 'fb-extra-7',
    orderId: 'ord-extra-7',
    studentId: 'stu-2',
    teacherId: 'user-tutor-1',
    date: '2024-02-02',
    startTime: '18:00',
    endTime: '19:30',
    deductHours: '1.5',
    content: '中考政治时事热点分析，讲解了答题技巧。',
    methods: '观点+原理+联系实际',
    mistakes: '答案要点不全面',
    performance: '思维活跃，但答题不够规范',
    homework: '整理时事热点笔记',
    parentFeedback: {
      rating: 3,
      tags: ['🤔 讲解不够清楚'],
      evaluation: {
        knowledge_absorption: '一般',
        student_explain: '无',
        professionalism: '基本专业',
        responsibility: '被动回应',
        patience: '一般耐心',
        post_feedback: '简单概括',
        punctuality: '基本守时',
        camera: '开',
        network: '网络通畅',
        environment: '嘈杂',
      },
      remarks: '孩子觉得政治课有点枯燥',
      submittedAt: new Date('2024-02-03T08:30:00')
    },
    createdAt: new Date('2024-02-02T19:40:00'),
    updatedAt: new Date('2024-02-02T19:40:00')
  },
  {
    id: 'fb-extra-8',
    orderId: 'ord-extra-8',
    studentId: 'stu-3',
    teacherId: 'user-tutor-1',
    date: '2024-02-04',
    startTime: '16:00',
    endTime: '18:00',
    deductHours: '2',
    content: '小升初数学综合复习，重点讲解了应用题解题思路。',
    methods: '画图分析法',
    mistakes: '单位换算容易出错',
    performance: '基础扎实，解题速度快',
    homework: '完成综合应用题15道',
    createdAt: new Date('2024-02-04T18:10:00'),
    updatedAt: new Date('2024-02-04T18:10:00')
  },
  {
    id: 'fb-extra-9',
    orderId: 'ord-extra-9',
    studentId: 'stu-4',
    teacherId: 'user-tutor-1',
    date: '2024-02-06',
    startTime: '19:30',
    endTime: '21:00',
    deductHours: '1.5',
    content: '英语语法专题：现在完成时的用法及练习。',
    methods: '时间轴对比法',
    mistakes: '过去分词拼写错误',
    performance: '语法理解较好，需要多练习',
    homework: '完成现在完成时练习题',
    parentFeedback: {
      rating: 4,
      tags: ['🧘 无明显问题'],
      evaluation: {
        knowledge_absorption: '较好',
        student_explain: '有',
        professionalism: '专业严谨',
        responsibility: '主动关注',
        patience: '非常耐心',
        post_feedback: '及时详细',
        punctuality: '很守时',
        camera: '开',
        network: '网络较卡',
        environment: '安静',
      },
      remarks: '希望老师多布置一些练习题',
      submittedAt: new Date('2024-02-07T09:00:00')
    },
    createdAt: new Date('2024-02-06T21:10:00'),
    updatedAt: new Date('2024-02-06T21:10:00')
  },
  {
    id: 'fb-extra-10',
    orderId: 'ord-extra-10',
    studentId: 'stu-5',
    teacherId: 'user-tutor-1',
    date: '2024-02-08',
    startTime: '18:00',
    endTime: '19:30',
    deductHours: '1.5',
    content: '力学综合复习，讲解了力的合成与分解。',
    methods: '平行四边形法则',
    mistakes: '力的方向判断有误',
    performance: '计算能力强，理解力稍弱',
    homework: '完成力学计算题20道',
    createdAt: new Date('2024-02-08T19:40:00'),
    updatedAt: new Date('2024-02-08T19:40:00')
  },
  {
    id: 'fb-extra-11',
    orderId: 'ord-2',
    studentId: 'stu-1',
    teacherId: 'user-tutor-1',
    date: '2024-02-10',
    startTime: '18:00',
    endTime: '20:00',
    deductHours: '2',
    content: '二次函数综合应用，讲解了函数与几何综合题。',
    methods: '数形结合',
    mistakes: '坐标计算容易出错',
    performance: '思维严谨，解题规范',
    homework: '完成二次函数综合题10道',
    parentFeedback: {
      rating: 5,
      tags: ['🧘 无明显问题'],
      evaluation: {
        knowledge_absorption: '很好',
        student_explain: '有',
        professionalism: '专业严谨',
        responsibility: '主动关注',
        patience: '非常耐心',
        post_feedback: '及时详细',
        punctuality: '很守时',
        camera: '开',
        network: '网络通畅',
        environment: '安静',
      },
      remarks: '孩子数学进步很大',
      submittedAt: new Date('2024-02-11T08:00:00')
    },
    createdAt: new Date('2024-02-10T20:10:00'),
    updatedAt: new Date('2024-02-10T20:10:00')
  },
  {
    id: 'fb-extra-12',
    orderId: 'ord-extra-1',
    studentId: 'stu-1',
    teacherId: 'user-tutor-1',
    date: '2024-02-12',
    startTime: '19:00',
    endTime: '20:30',
    deductHours: '1.5',
    content: '英语写作训练，重点讲解了议论文的结构。',
    methods: '三段式写作法',
    mistakes: '连接词使用不当',
    performance: '词汇量丰富，但文章结构需要加强',
    homework: '写一篇议论文作文',
    createdAt: new Date('2024-02-12T20:40:00'),
    updatedAt: new Date('2024-02-12T20:40:00')
  },

  // 试课课后反馈演示（订单 ord-feedback-trial-done-with-feedback）
  {
    id: 'fb-trial-demo-with-parent',
    orderId: 'ord-feedback-trial-done-with-feedback',
    studentId: 'stu-feedback-t-d',
    studentName: '周思源',
    teacherId: 'user-tutor-1',
    date: '2026-05-01',
    startTime: '10:00',
    endTime: '11:00',
    deductHours: '1',
    feeStandardGrade: '五年级',
    studentAttendance: '按时上课',
    homeworkCompletion: '没有布置作业',
    content:
      '[试课演示] 本节课梳理了五年级语文阅读题的审题步骤，讲解了概括段意与人物形象分析的典型问法。',
    methods: '四步阅读：标关键词—划中心句—联上下文—回看题干',
    mistakes: '作答时要点遗漏较多，需注意分点作答',
    performance: '课堂专注度好，能与老师互动复述要点',
    homework: '完成一篇课外阅读并完成两道开放题作答',
    parentFeedback: {
      rating: 5,
      tags: ['🧘 无明显问题'],
      evaluation: {
        knowledge_absorption: '很好',
        student_explain: '有',
        professionalism: '专业严谨',
        responsibility: '主动关注',
        patience: '非常耐心',
        post_feedback: '及时详细',
        punctuality: '很守时',
        camera: '开',
        network: '网络通畅',
        environment: '安静',
      },
      remarks: '试课老师讲得很清楚，孩子愿意继续跟',
      submittedAt: new Date('2026-05-01T20:30:00'),
    },
    createdAt: new Date('2026-05-01T11:30:00'),
    updatedAt: new Date('2026-05-01T11:30:00'),
  },

  // 试课课后反馈演示（订单 ord-feedback-trial-done-tutor-only，无家长反馈）
  {
    id: 'fb-trial-demo-tutor-only',
    orderId: 'ord-feedback-trial-done-tutor-only',
    studentId: 'stu-feedback-t-e',
    studentName: '周艺涵',
    teacherId: 'user-tutor-1',
    date: '2026-05-05',
    startTime: '19:00',
    endTime: '20:00',
    deductHours: '1',
    feeStandardGrade: '九年级',
    studentAttendance: '按时上课',
    homeworkCompletion: '没有布置作业',
    content:
      '[试课演示] 化学用语与方程式书写入门：物质的量初步、化学式读写与方程式配平示意。',
    methods: '先写产物再配平，守恒检查一遍',
    mistakes: '方程式条件与箭头容易漏写',
    performance: '基础尚可，方程式书写需放慢节奏巩固',
    homework: '整理本节课方程式 3 条并抄写在错题本',
    createdAt: new Date('2026-05-05T20:15:00'),
    updatedAt: new Date('2026-05-05T20:15:00'),
  },
]
