import { Role } from '@/types'
import type { HeaderNavConfig } from '@/types'

export const mockHeaderNavConfigs: HeaderNavConfig[] = [
  {
    id: 'hn-1',
    title: '工作台',
    href: '/',
    icon: 'LayoutDashboard',
    external: false,
    emphasis: false,
    visibleRoles: [Role.SALES, Role.TUTOR, Role.MANAGER, Role.OPERATOR, Role.ADMIN],
    sortOrder: 1,
    enabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'hn-2',
    title: '数据大屏',
    href: '/analytics',
    icon: 'LineChart',
    external: false,
    emphasis: true,
    visibleRoles: [Role.SALES, Role.TUTOR, Role.MANAGER, Role.OPERATOR, Role.ADMIN],
    sortOrder: 2,
    enabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'hn-3',
    title: '帮助中心',
    href: 'https://help.eduflow.example',
    icon: 'HelpCircle',
    external: true,
    emphasis: false,
    visibleRoles: [Role.SALES, Role.TUTOR, Role.MANAGER, Role.OPERATOR, Role.ADMIN],
    sortOrder: 3,
    enabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'hn-4',
    title: '产品动态',
    href: 'https://changelog.eduflow.example',
    icon: 'Megaphone',
    external: true,
    emphasis: false,
    visibleRoles: [Role.SALES, Role.TUTOR, Role.MANAGER, Role.OPERATOR, Role.ADMIN],
    sortOrder: 4,
    enabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'hn-5',
    title: '培训中心',
    href: 'https://learn.eduflow.example',
    icon: 'GraduationCap',
    external: true,
    emphasis: false,
    visibleRoles: [Role.SALES, Role.TUTOR, Role.MANAGER, Role.OPERATOR, Role.ADMIN],
    sortOrder: 5,
    enabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'hn-6',
    title: '合规公告',
    href: 'https://compliance.eduflow.example',
    icon: 'ShieldCheck',
    external: true,
    emphasis: false,
    visibleRoles: [Role.SALES, Role.TUTOR, Role.MANAGER, Role.OPERATOR, Role.ADMIN],
    sortOrder: 6,
    enabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'hn-7',
    title: '开放平台',
    href: 'https://open.eduflow.example',
    icon: 'Plug',
    external: true,
    emphasis: false,
    visibleRoles: [Role.OPERATOR, Role.ADMIN],
    sortOrder: 7,
    enabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'hn-8',
    title: '客服中心',
    href: 'https://support.eduflow.example',
    icon: 'Headphones',
    external: true,
    emphasis: false,
    visibleRoles: [Role.SALES, Role.TUTOR, Role.MANAGER, Role.OPERATOR, Role.ADMIN],
    sortOrder: 8,
    enabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'hn-9',
    title: '下载客户端',
    href: 'https://download.eduflow.example',
    icon: 'Download',
    external: true,
    emphasis: false,
    visibleRoles: [Role.SALES, Role.TUTOR, Role.MANAGER, Role.OPERATOR, Role.ADMIN],
    sortOrder: 9,
    enabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'hn-10',
    title: '官网',
    href: 'https://www.eduflow.example',
    icon: 'Globe',
    external: true,
    emphasis: true,
    visibleRoles: [Role.SALES, Role.TUTOR, Role.MANAGER, Role.OPERATOR, Role.ADMIN],
    sortOrder: 10,
    enabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
