import { ManagementIncomeDetail, ManagementIncomeSubType } from '@/types'

export const mockManagementIncomeDetails: ManagementIncomeDetail[] = [
  // 第1条：教练管理费，团队负责人是自己（以陈总监登录为例）
  {
    id: 'mgmt-income-1',
    teamLeaderId: 'user-manager-0',
    teamLeaderName: '陈总监',
    teamLeaderPhone: '13800003000',
    teamLeaderRank: '总监',
    regularLessonCount: 45,
    subType: ManagementIncomeSubType.TUTOR_MGMT_FEE,
    amount: 225,
    occurredAt: new Date('2026-04-30'),
    createdAt: new Date('2026-05-01'),
  },
  // 第2条：正式学管 → 学管管理费
  {
    id: 'mgmt-income-2',
    teamLeaderId: 'user-manager-2',
    teamLeaderName: '李学管',
    teamLeaderPhone: '13800003002',
    teamLeaderRank: '正式学管',
    regularLessonCount: 280,
    subType: ManagementIncomeSubType.MANAGER_MGMT_FEE,
    amount: 1400,
    occurredAt: new Date('2026-04-30'),
    createdAt: new Date('2026-05-01'),
  },
  // 第3条：见习学管 → 学管管理费
  {
    id: 'mgmt-income-3',
    teamLeaderId: 'user-manager-3',
    teamLeaderName: '张学管',
    teamLeaderPhone: '13800003003',
    teamLeaderRank: '见习学管',
    regularLessonCount: 210,
    subType: ManagementIncomeSubType.MANAGER_MGMT_FEE,
    amount: 1050,
    occurredAt: new Date('2026-04-30'),
    createdAt: new Date('2026-05-01'),
  },
  // 第4条：见习学管（王学管下属）→ 学管管理费
  {
    id: 'mgmt-income-4',
    teamLeaderId: 'user-manager-4',
    teamLeaderName: '赵学管',
    teamLeaderPhone: '13800003004',
    teamLeaderRank: '见习学管',
    regularLessonCount: 60,
    subType: ManagementIncomeSubType.MANAGER_MGMT_FEE,
    amount: 300,
    occurredAt: new Date('2026-04-30'),
    createdAt: new Date('2026-05-01'),
  },
  // 第5条：正式学管（王学管下属）→ 学管管理费
  {
    id: 'mgmt-income-5',
    teamLeaderId: 'user-manager-5',
    teamLeaderName: '钱学管',
    teamLeaderPhone: '13800003005',
    teamLeaderRank: '正式学管',
    regularLessonCount: 140,
    subType: ManagementIncomeSubType.MANAGER_MGMT_FEE,
    amount: 700,
    occurredAt: new Date('2026-04-30'),
    createdAt: new Date('2026-05-01'),
  },
  // 第6条：见习学管（李学管下属）→ 学管管理费
  {
    id: 'mgmt-income-6',
    teamLeaderId: 'user-manager-6',
    teamLeaderName: '孙学管',
    teamLeaderPhone: '13800003006',
    teamLeaderRank: '见习学管',
    regularLessonCount: 85,
    subType: ManagementIncomeSubType.MANAGER_MGMT_FEE,
    amount: 425,
    occurredAt: new Date('2026-04-30'),
    createdAt: new Date('2026-05-01'),
  },
  // 第7条：正式学管（李学管下属）→ 学管管理费
  {
    id: 'mgmt-income-7',
    teamLeaderId: 'user-manager-7',
    teamLeaderName: '周学管',
    teamLeaderPhone: '13800003007',
    teamLeaderRank: '正式学管',
    regularLessonCount: 120,
    subType: ManagementIncomeSubType.MANAGER_MGMT_FEE,
    amount: 600,
    occurredAt: new Date('2026-04-30'),
    createdAt: new Date('2026-05-01'),
  },
  // 第8条：见习学管（张学管下属）→ 学管管理费
  {
    id: 'mgmt-income-8',
    teamLeaderId: 'user-manager-8',
    teamLeaderName: '吴学管',
    teamLeaderPhone: '13800003008',
    teamLeaderRank: '见习学管',
    regularLessonCount: 55,
    subType: ManagementIncomeSubType.MANAGER_MGMT_FEE,
    amount: 275,
    occurredAt: new Date('2026-04-30'),
    createdAt: new Date('2026-05-01'),
  },
  // 第9条：正式学管（张学管下属）→ 学管管理费
  {
    id: 'mgmt-income-9',
    teamLeaderId: 'user-manager-9',
    teamLeaderName: '郑学管',
    teamLeaderPhone: '13800003009',
    teamLeaderRank: '正式学管',
    regularLessonCount: 95,
    subType: ManagementIncomeSubType.MANAGER_MGMT_FEE,
    amount: 475,
    occurredAt: new Date('2026-04-30'),
    createdAt: new Date('2026-05-01'),
  },
  // 第10条：总监（王学管已晋升为总监）→ 总监培养费（1元/课时）
  {
    id: 'mgmt-income-10',
    teamLeaderId: 'user-manager-1',
    teamLeaderName: '王学管',
    teamLeaderPhone: '13800003001',
    teamLeaderRank: '总监',
    regularLessonCount: 320,
    subType: ManagementIncomeSubType.DIRECTOR_TRAIN_FEE,
    amount: 320,
    occurredAt: new Date('2026-04-30'),
    createdAt: new Date('2026-05-01'),
  },
  // 王学管 → 教练管理费（5元/课时，直管教练团队）
  {
    id: 'mgmt-income-11',
    teamLeaderId: 'user-manager-1',
    teamLeaderName: '王学管',
    teamLeaderPhone: '13800003001',
    teamLeaderRank: '总监',
    regularLessonCount: 180,
    subType: ManagementIncomeSubType.TUTOR_MGMT_FEE,
    amount: 900,
    occurredAt: new Date('2026-04-30'),
    createdAt: new Date('2026-05-01'),
  },
]
