import { Order, OrderStatus, OrderType } from '@/types'

export const mockOrders: Order[] = [
  {
    id: 'ord-1',
    type: OrderType.TRIAL,
    status: OrderStatus.COMPLETED,
    studentId: 'stu-1',
    salesPersonId: 'user-sales-1',
    managerId: 'user-manager-1',
    subject: '数学',
    grade: '四年级',
    totalHours: 1,
    remainingHours: 0,
    scheduledAt: new Date('2023-09-02T10:00:00'),
    assignedTeacherId: 'user-tutor-1',
    price: 0,
    createdAt: new Date('2023-09-01T14:00:00'),
    updatedAt: new Date('2023-09-02T11:00:00')
  },
  {
    id: 'ord-2',
    type: OrderType.REGULAR,
    status: OrderStatus.IN_PROGRESS,
    studentId: 'stu-1',
    salesPersonId: 'user-sales-1',
    managerId: 'user-manager-1',
    subject: '数学',
    grade: '四年级',
    totalHours: 40,
    remainingHours: 32,
    assignedTeacherId: 'user-tutor-1',
    price: 6000,
    createdAt: new Date('2023-09-05T09:00:00'),
    updatedAt: new Date('2023-09-05T09:00:00'),
    // Extended fields
    lastExamScore: "95",
    examMaxScore: "100",
    textbookVersion: "人教版",
    campusName: "北京校区",
    campusAccount: "beijing_01",
    studentAccount: "stu_001",
    remarks: "学生基础扎实，希望进行拔高训练。",
    weeklySchedule: [
      { day: "monday", startTime: "18:00", endTime: "20:00" },
      { day: "saturday", startTime: "10:00", endTime: "12:00" }
    ],
    transactions: [
        { id: 'tx-2-1', type: 'INITIAL', amount: 6000, hours: 40, createdAt: new Date('2023-09-05T09:00:00') }
    ]
  },
  {
    id: 'ord-3',
    type: OrderType.TRIAL,
    status: OrderStatus.PENDING,
    studentId: 'stu-2',
    salesPersonId: 'user-sales-1',
    managerId: 'user-manager-1',
    subject: '英语',
    grade: '初二',
    totalHours: 1,
    remainingHours: 1,
    price: 0,
    applicantIds: ['user-tutor-1', 'user-tutor-2', 'user-tutor-3'],
    createdAt: new Date(),
    updatedAt: new Date(),
    lastExamScore: "85",
    examMaxScore: "120",
    textbookVersion: "仁爱版",
    campusName: "上海校区",
    campusAccount: "shanghai_01",
    studentAccount: "stu_002",
    scheduledAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // 2 days later
    remarks: "口语较弱，希望加强对话练习"
  },
  {
    id: 'ord-4',
    type: OrderType.REGULAR,
    status: OrderStatus.ASSIGNED,
    studentId: 'stu-3',
    salesPersonId: 'user-sales-1',
    subject: '语文',
    grade: '五年级',
    totalHours: 20,
    remainingHours: 20,
    assignedTeacherId: 'user-tutor-1',
    price: 3000,
    createdAt: new Date('2023-11-25T15:30:00'),
    updatedAt: new Date('2023-11-26T10:00:00'),
    lastExamScore: "88",
    examMaxScore: "100",
    textbookVersion: "部编版",
    campusName: "广州校区",
    campusAccount: "guangzhou_01",
    studentAccount: "stu_003",
    weeklySchedule: [
       { day: "friday", startTime: "16:30", endTime: "18:30" }
    ],
    remarks: "作文写不长，阅读理解扣分多",
    transactions: [
        { id: 'tx-4-1', type: 'INITIAL', amount: 3000, hours: 20, createdAt: new Date('2023-11-25T15:30:00') }
    ]
  },
  {
    id: 'ord-5',
    type: OrderType.TRIAL,
    status: OrderStatus.CANCELLED,
    studentId: 'stu-4',
    salesPersonId: 'user-sales-1',
    subject: '物理',
    grade: '高一',
    totalHours: 1,
    remainingHours: 1,
    price: 0,
    createdAt: new Date('2024-01-10T11:00:00'),
    updatedAt: new Date('2024-01-11T16:00:00'),
    lastExamScore: "60",
    examMaxScore: "100",
    campusName: "深圳校区",
    campusAccount: "shenzhen_01",
    studentAccount: "stu_004",
    remarks: "学生临时有事取消"
  },
  {
    id: 'ord-6',
    type: OrderType.TRIAL,
    status: OrderStatus.COMPLETED,
    studentId: 'stu-3',
    salesPersonId: 'user-sales-1',
    subject: '物理',
    grade: '初三',
    totalHours: 1,
    remainingHours: 0,
    scheduledAt: new Date('2024-02-01T14:00:00'),
    assignedTeacherId: 'user-tutor-2',
    price: 0,
    createdAt: new Date('2024-01-28T10:00:00'),
    updatedAt: new Date('2024-02-01T15:00:00'),
    lastExamScore: "75",
    examMaxScore: "100",
    campusName: "广州校区",
    campusAccount: "guangzhou_01",
    studentAccount: "stu_003",
    remarks: "试课效果不错，已转化"
  },
  {
    id: 'ord-7',
    type: OrderType.TRIAL,
    status: OrderStatus.COMPLETED,
    studentId: 'stu-5',
    salesPersonId: 'user-sales-1',
    subject: '英语',
    grade: '三年级',
    totalHours: 1,
    remainingHours: 0,
    scheduledAt: new Date('2024-02-05T16:00:00'),
    assignedTeacherId: 'user-tutor-3',
    price: 0,
    createdAt: new Date('2024-02-01T09:00:00'),
    updatedAt: new Date('2024-02-05T17:00:00'),
    campusName: "杭州校区",
    campusAccount: "hangzhou_01",
    studentAccount: "stu_005",
    remarks: "零基础启蒙"
  },
  {
    id: 'ord-8',
    type: OrderType.REGULAR,
    status: OrderStatus.COMPLETED,
    studentId: 'stu-2',
    salesPersonId: 'user-sales-1',
    subject: '数学',
    grade: '初二',
    totalHours: 20,
    remainingHours: 0,
    assignedTeacherId: 'user-tutor-2',
    price: 4400,
    createdAt: new Date('2023-10-01T14:00:00'),
    updatedAt: new Date('2023-12-01T15:00:00'),
    weeklySchedule: [
      { day: "sunday", startTime: "14:00", endTime: "16:00" }
    ],
    transactions: [
      { id: 'tx-8-1', type: 'INITIAL', amount: 4400, hours: 20, createdAt: new Date('2023-10-01T14:00:00') }
    ]
  },
  {
    id: 'ord-9',
    type: OrderType.REGULAR,
    status: OrderStatus.COMPLETED,
    studentId: 'stu-4',
    salesPersonId: 'user-sales-1',
    subject: '化学',
    grade: '高一',
    totalHours: 10,
    remainingHours: 1,
    assignedTeacherId: 'user-tutor-3',
    price: 2800,
    createdAt: new Date('2024-01-01T10:00:00'),
    updatedAt: new Date('2024-02-15T11:00:00'),
    weeklySchedule: [
      { day: "wednesday", startTime: "19:00", endTime: "21:00" }
    ],
    transactions: [
      { id: 'tx-9-1', type: 'INITIAL', amount: 2800, hours: 10, createdAt: new Date('2024-01-01T10:00:00') },
      { id: 'tx-9-2', type: 'RENEWAL', amount: 1400, hours: 5, createdAt: new Date('2024-02-01T15:00:00') }
    ]
  },
  // Market Demo Orders for persistent navigation testing
  {
    id: "market-demo-1",
    type: OrderType.TRIAL,
    status: OrderStatus.PENDING,
    studentId: "stu-demo-1",
    salesPersonId: "sales-1",
    managerId: 'user-manager-1',
    subject: "数学",
    grade: "初二",
    totalHours: 1,
    remainingHours: 1,
    price: 0,
    applicantIds: ['user-tutor-4', 'user-tutor-5'],
    createdAt: new Date(Date.now() - 5 * 60 * 1000), // 5 mins ago
    updatedAt: new Date(),
    scheduledAt: new Date(Date.now() + 24 * 60 * 60 * 1000), // Tomorrow
    lastExamScore: "88",
    examMaxScore: "100",
    remarks: "基础薄弱，需要耐心辅导"
  },
  {
    id: "market-demo-2",
    type: OrderType.REGULAR,
    status: OrderStatus.PENDING,
    studentId: "stu-demo-2",
    salesPersonId: "sales-1",
    subject: "英语",
    grade: "高一",
    totalHours: 40,
    remainingHours: 40,
    price: 8000,
    createdAt: new Date(Date.now() - 15 * 60 * 1000), // 15 mins ago
    updatedAt: new Date(),
    weeklySchedule: [{ day: "saturday", startTime: "14:00", endTime: "16:00" }],
    lastExamScore: "110",
    examMaxScore: "150",
    remarks: "目标冲刺重点班"
  },
  {
    id: "refund-demo-1",
    type: OrderType.REGULAR,
    status: OrderStatus.CANCEL_REQUESTED,
    studentId: "stu-demo-2",
    salesPersonId: "sales-1",
    managerId: 'user-manager-1',
    subject: "化学",
    grade: "高一",
    totalHours: 20,
    remainingHours: 15,
    price: 4000,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
    updatedAt: new Date(),
    weeklySchedule: [{ day: "sunday", startTime: "10:00", endTime: "12:00" }],
    cancelReason: "学生跟不上进度，家长要求换机构",
    refundAmount: 3000,
    remarks: "需要尽快处理"
  }
]
