import { RefundApplicationStatus, type RefundApplication } from '@/types'

/** 与 mockOrders 中 refund-demo-1 配套的演示退费申请（一审待审） */
export const mockRefundApplications: RefundApplication[] = [
  {
    id: 'rfa-demo-seed-1',
    orderId: 'refund-demo-1',
    applicantUserId: 'sales-1',
    applicantName: '演示招生',
    refundKind: 'REGULAR',
    status: RefundApplicationStatus.PENDING_FIRST_REVIEW,
    reason: '学生跟不上进度，家长要求换机构',
    requestedAmount: 2700,
    userOriginalRequestedAmount: 2700,
    computedMaxAtApply: 2700,
    breakdown: {
      totalFee: 4000,
      totalHours: 20,
      consumedHours: 5,
      remainingHours: 15,
      nonRefundableAmount: 400,
      consumedLessonFee: 900,
      maxRefundable: 2700,
    },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  // 试课场景：79.9（已上完 / 未上课 / 已分配）
  {
    id: 'rfa-scn-trial-done-p1',
    orderId: 'rfd-trial-done-799',
    applicantUserId: 'user-sales-1',
    applicantName: '张招生',
    refundKind: 'TRIAL',
    status: RefundApplicationStatus.PENDING_FIRST_REVIEW,
    reason: '已上完试课，家长要求退款测试一审通过流程',
    requestedAmount: 79,
    userOriginalRequestedAmount: 79,
    computedMaxAtApply: 79,
    createdAt: new Date('2025-09-08T10:00:00'),
    updatedAt: new Date('2025-09-08T10:00:00'),
  },
  {
    id: 'rfa-scn-trial-unstart-r1',
    orderId: 'rfd-trial-unstarted-799',
    applicantUserId: 'user-sales-1',
    applicantName: '张招生',
    refundKind: 'TRIAL',
    status: RefundApplicationStatus.FIRST_REJECTED,
    reason: '未上课退费，测试一审驳回',
    requestedAmount: 79,
    userOriginalRequestedAmount: 79,
    computedMaxAtApply: 79,
    firstReviewNote: '资料不完整，先补充家长确认记录',
    firstRejectApplicantNote: '缺少家长书面确认，暂不通过',
    firstReviewerId: 'user-operator-1',
    firstReviewerName: '运营专员',
    firstReviewedAt: new Date('2025-09-08T12:00:00'),
    createdAt: new Date('2025-09-08T09:00:00'),
    updatedAt: new Date('2025-09-08T12:00:00'),
  },
  {
    id: 'rfa-scn-trial-assigned-p2',
    orderId: 'rfd-trial-assigned-799',
    applicantUserId: 'user-sales-2',
    applicantName: '李销售',
    refundKind: 'TRIAL',
    status: RefundApplicationStatus.PENDING_SECOND_REVIEW,
    reason: '未开课前用户申请退款，测试待二审',
    requestedAmount: 79,
    userOriginalRequestedAmount: 79,
    computedMaxAtApply: 79,
    firstReviewNote: '一审同意，转二审复核',
    firstReviewerId: 'user-operator-1',
    firstReviewerName: '运营专员',
    firstReviewedAt: new Date('2025-09-08T13:10:00'),
    createdAt: new Date('2025-09-08T12:30:00'),
    updatedAt: new Date('2025-09-08T13:10:00'),
  },

  // 正课 30/50/80/100：覆盖一审通过/二审驳回/二审通过成功/二审通过失败
  {
    id: 'rfa-scn-reg-30-p2',
    orderId: 'rfd-regular-30-c0',
    applicantUserId: 'user-sales-1',
    applicantName: '张招生',
    refundKind: 'REGULAR',
    status: RefundApplicationStatus.PENDING_SECOND_REVIEW,
    reason: '未消课退费，测试一审后待二审',
    requestedAmount: 3900,
    userOriginalRequestedAmount: 3900,
    computedMaxAtApply: 3900,
    breakdown: {
      totalFee: 4500,
      totalHours: 30,
      consumedHours: 0,
      remainingHours: 30,
      nonRefundableAmount: 600,
      consumedLessonFee: 0,
      maxRefundable: 3900,
    },
    firstReviewNote: '金额无误，待二审',
    firstReviewerId: 'user-operator-1',
    firstReviewerName: '运营专员',
    firstReviewedAt: new Date('2025-09-09T10:00:00'),
    createdAt: new Date('2025-09-09T09:00:00'),
    updatedAt: new Date('2025-09-09T10:00:00'),
  },
  {
    id: 'rfa-scn-reg-50-second-reject',
    orderId: 'rfd-regular-50-c20',
    applicantUserId: 'user-sales-1',
    applicantName: '张招生',
    refundKind: 'REGULAR',
    // 二审驳回后退回一审队列
    status: RefundApplicationStatus.PENDING_FIRST_REVIEW,
    reason: '已消 20 课时，申请部分退费',
    requestedAmount: 4000,
    userOriginalRequestedAmount: 4200,
    computedMaxAtApply: 4200,
    breakdown: {
      totalFee: 8000,
      totalHours: 50,
      consumedHours: 20,
      remainingHours: 30,
      nonRefundableAmount: 1000,
      consumedLessonFee: 2800,
      maxRefundable: 4200,
    },
    firstReviewNote: '一审通过，金额从 4200 调整为 4000',
    firstReviewerId: 'user-operator-1',
    firstReviewerName: '运营专员',
    firstReviewedAt: new Date('2025-09-09T11:00:00'),
    secondReviewNote: '二审驳回，需补充回访录音',
    secondRejectApplicantNote: '缺少回访录音，退回一审补件',
    secondReviewerId: 'user-operator-1',
    secondReviewerName: '运营专员',
    secondReviewedAt: new Date('2025-09-09T13:00:00'),
    createdAt: new Date('2025-09-09T10:20:00'),
    updatedAt: new Date('2025-09-09T13:00:00'),
  },
  {
    id: 'rfa-scn-reg-80-success',
    orderId: 'rfd-regular-80-c70',
    applicantUserId: 'user-sales-2',
    applicantName: '李销售',
    refundKind: 'RENEWAL',
    status: RefundApplicationStatus.REFUND_SUCCESS,
    reason: '续课部分退费，测试二审通过成功',
    requestedAmount: 1200,
    userOriginalRequestedAmount: 1500,
    computedMaxAtApply: 1500,
    breakdown: {
      totalFee: 13600,
      totalHours: 80,
      consumedHours: 70,
      remainingHours: 10,
      nonRefundableAmount: 1600,
      consumedLessonFee: 10500,
      maxRefundable: 1500,
    },
    firstReviewNote: '一审调整金额 1500 -> 1200',
    firstReviewerId: 'user-operator-1',
    firstReviewerName: '运营专员',
    firstReviewedAt: new Date('2025-09-09T14:00:00'),
    secondReviewNote: '同意退款',
    secondReviewerId: 'user-operator-1',
    secondReviewerName: '运营专员',
    secondReviewedAt: new Date('2025-09-09T15:00:00'),
    finalRefundAmount: 1200,
    executionStatus: 'SUCCESS',
    createdAt: new Date('2025-09-09T13:30:00'),
    updatedAt: new Date('2025-09-09T15:00:00'),
  },
  {
    id: 'rfa-scn-reg-100-failed',
    orderId: 'rfd-regular-100-c99',
    applicantUserId: 'user-sales-3',
    applicantName: '王业绩',
    refundKind: 'REGULAR',
    status: RefundApplicationStatus.REFUND_FAILED,
    reason: '接近完课，测试小额退款失败链路',
    requestedAmount: 120,
    userOriginalRequestedAmount: 160,
    computedMaxAtApply: 160,
    breakdown: {
      totalFee: 18000,
      totalHours: 100,
      consumedHours: 99,
      remainingHours: 1,
      nonRefundableAmount: 2000,
      consumedLessonFee: 15840,
      maxRefundable: 160,
    },
    firstReviewNote: '一审调整金额 160 -> 120',
    firstReviewerId: 'user-operator-1',
    firstReviewerName: '运营专员',
    firstReviewedAt: new Date('2025-09-09T16:00:00'),
    secondReviewNote: '二审通过，执行失败',
    secondReviewerId: 'user-operator-1',
    secondReviewerName: '运营专员',
    secondReviewedAt: new Date('2025-09-09T16:20:00'),
    finalRefundAmount: 120,
    executionStatus: 'FAILED',
    createdAt: new Date('2025-09-09T15:30:00'),
    updatedAt: new Date('2025-09-09T16:20:00'),
  },

  // 转正红包：小学/初中/高中
  {
    id: 'rfa-scn-rp-primary-p1',
    orderId: 'rfd-red-primary',
    applicantUserId: 'user-sales-1',
    applicantName: '张招生',
    refundKind: 'RED_PACKET',
    status: RefundApplicationStatus.PENDING_FIRST_REVIEW,
    reason: '小学转正红包退费测试',
    requestedAmount: 299,
    userOriginalRequestedAmount: 299,
    computedMaxAtApply: 299,
    createdAt: new Date('2025-09-10T09:00:00'),
    updatedAt: new Date('2025-09-10T09:00:00'),
  },
  {
    id: 'rfa-scn-rp-junior-p2',
    orderId: 'rfd-red-junior',
    applicantUserId: 'user-sales-2',
    applicantName: '李销售',
    refundKind: 'RED_PACKET',
    status: RefundApplicationStatus.PENDING_SECOND_REVIEW,
    reason: '初中转正红包退费，待二审',
    requestedAmount: 380,
    userOriginalRequestedAmount: 399,
    computedMaxAtApply: 399,
    firstReviewNote: '一审调整红包退款 399 -> 380',
    firstReviewerId: 'user-operator-1',
    firstReviewerName: '运营专员',
    firstReviewedAt: new Date('2025-09-10T11:00:00'),
    createdAt: new Date('2025-09-10T10:20:00'),
    updatedAt: new Date('2025-09-10T11:00:00'),
  },
  {
    id: 'rfa-scn-rp-high-r1',
    orderId: 'rfd-red-high',
    applicantUserId: 'user-sales-3',
    applicantName: '王业绩',
    refundKind: 'RED_PACKET',
    status: RefundApplicationStatus.FIRST_REJECTED,
    reason: '高中转正红包退费，测试一审驳回',
    requestedAmount: 199,
    userOriginalRequestedAmount: 199,
    computedMaxAtApply: 199,
    firstReviewNote: '材料不齐，驳回补件',
    firstRejectApplicantNote: '缺少家长签字确认，暂不通过',
    firstReviewerId: 'user-operator-1',
    firstReviewerName: '运营专员',
    firstReviewedAt: new Date('2025-09-10T12:10:00'),
    createdAt: new Date('2025-09-10T11:30:00'),
    updatedAt: new Date('2025-09-10T12:10:00'),
  },
]
