import { TutorCreditRule, TutorCreditRuleCategory } from '@/types'

const now = new Date('2026-01-01T00:00:00.000Z')

export const mockTutorCreditRules: TutorCreditRule[] = [
  // ── 轻微违规（扣1分）──
  {
    id: 'tcr-minor-01',
    category: TutorCreditRuleCategory.MINOR,
    title: '试听课后未开通数学G账号',
    description: '试听课结束后，没有给学生开通数学G账号',
    scoreDelta: -1,
    isEnabled: true,
    sortOrder: 10,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-minor-02',
    category: TutorCreditRuleCategory.MINOR,
    title: '无课堂视频录制文件',
    description: '试听课或正课，没有课堂视频录制文件',
    scoreDelta: -1,
    isEnabled: true,
    sortOrder: 20,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-minor-03',
    category: TutorCreditRuleCategory.MINOR,
    title: '课后反馈未在1小时内提交',
    description: '课后反馈未在 1 小时内提交',
    scoreDelta: -1,
    isEnabled: true,
    sortOrder: 30,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-minor-04',
    category: TutorCreditRuleCategory.MINOR,
    title: '作业批改超过24小时',
    description: '作业批改超过 24 小时',
    scoreDelta: -1,
    isEnabled: true,
    sortOrder: 40,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-minor-05',
    category: TutorCreditRuleCategory.MINOR,
    title: '学管提醒后8小时内未回复',
    description: '学管提醒后未在 8 小时内及时回复',
    scoreDelta: -1,
    isEnabled: true,
    sortOrder: 50,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-minor-06',
    category: TutorCreditRuleCategory.MINOR,
    title: '群内简单问题8小时内未答疑',
    description: '群内简单问题未在 8 小时内及时答疑',
    scoreDelta: -1,
    isEnabled: true,
    sortOrder: 60,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-minor-07',
    category: TutorCreditRuleCategory.MINOR,
    title: '未提前确认上课时间',
    description: '未提前确认上课时间',
    scoreDelta: -1,
    isEnabled: true,
    sortOrder: 70,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-minor-08',
    category: TutorCreditRuleCategory.MINOR,
    title: '微信头像另类被家长投诉',
    description: '微信头像另类被家长投诉',
    scoreDelta: -1,
    isEnabled: true,
    sortOrder: 80,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-minor-09',
    category: TutorCreditRuleCategory.MINOR,
    title: '微信名另类被家长投诉',
    description: '微信名另类被家长投诉',
    scoreDelta: -1,
    isEnabled: true,
    sortOrder: 90,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-minor-10',
    category: TutorCreditRuleCategory.MINOR,
    title: '进学生群未修改群名片',
    description: '进学生群，未修改群名片',
    scoreDelta: -1,
    isEnabled: true,
    sortOrder: 100,
    createdAt: now,
    updatedAt: now,
  },

  // ── 一般违规（扣3分）──
  {
    id: 'tcr-general-01',
    category: TutorCreditRuleCategory.GENERAL,
    title: '上课迟到',
    description: '上课迟到',
    scoreDelta: -3,
    isEnabled: true,
    sortOrder: 10,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-general-02',
    category: TutorCreditRuleCategory.GENERAL,
    title: '临时申请调课（提前24小时以内）',
    description: '临时申请调课，提前不足 24 小时',
    scoreDelta: -3,
    isEnabled: true,
    sortOrder: 20,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-general-03',
    category: TutorCreditRuleCategory.GENERAL,
    title: '未备课直接上课',
    description: '未备课直接上课',
    scoreDelta: -3,
    isEnabled: true,
    sortOrder: 30,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-general-04',
    category: TutorCreditRuleCategory.GENERAL,
    title: '12小时内未提交课后反馈',
    description: '12 小时内未提交课后反馈',
    scoreDelta: -3,
    isEnabled: true,
    sortOrder: 40,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-general-05',
    category: TutorCreditRuleCategory.GENERAL,
    title: '12小时内未批改作业',
    description: '12 小时内未批改作业',
    scoreDelta: -3,
    isEnabled: true,
    sortOrder: 50,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-general-06',
    category: TutorCreditRuleCategory.GENERAL,
    title: '12小时内未完成群内答疑',
    description: '12 小时内未完成群内答疑',
    scoreDelta: -3,
    isEnabled: true,
    sortOrder: 60,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-general-07',
    category: TutorCreditRuleCategory.GENERAL,
    title: '上课不讲普通话被家长投诉',
    description: '上课不讲普通话，被家长投诉',
    scoreDelta: -3,
    isEnabled: true,
    sortOrder: 70,
    createdAt: now,
    updatedAt: now,
  },

  // ── 严重违规（扣6分）──
  {
    id: 'tcr-severe-01',
    category: TutorCreditRuleCategory.SEVERE,
    title: '临时取消课程',
    description: '临时取消课程',
    scoreDelta: -6,
    isEnabled: true,
    sortOrder: 10,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-severe-02',
    category: TutorCreditRuleCategory.SEVERE,
    title: '不请假无故缺课',
    description: '不请假，无故缺课',
    scoreDelta: -6,
    isEnabled: true,
    sortOrder: 20,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-severe-03',
    category: TutorCreditRuleCategory.SEVERE,
    title: '主动向家长发送个人简历',
    description: '主动向家长发送个人简历',
    scoreDelta: -6,
    isEnabled: true,
    sortOrder: 30,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-severe-04',
    category: TutorCreditRuleCategory.SEVERE,
    title: '主动透露在校大学生身份',
    description: '主动透露在校大学生身份',
    scoreDelta: -6,
    isEnabled: true,
    sortOrder: 40,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-severe-05',
    category: TutorCreditRuleCategory.SEVERE,
    title: '未在10课时内进行阶段测试',
    description: '未在 10 课时内进行阶段测试',
    scoreDelta: -6,
    isEnabled: true,
    sortOrder: 50,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-severe-06',
    category: TutorCreditRuleCategory.SEVERE,
    title: '学习规划书未经学管审核擅自发布',
    description: '学习规划书未经过学管审核，擅自发布到家长群',
    scoreDelta: -6,
    isEnabled: true,
    sortOrder: 60,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-severe-07',
    category: TutorCreditRuleCategory.SEVERE,
    title: '试课后24小时内未提供学习规划书',
    description: '试课后未在 24 小时内向学生提供学习规划书',
    scoreDelta: -6,
    isEnabled: true,
    sortOrder: 70,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-severe-08',
    category: TutorCreditRuleCategory.SEVERE,
    title: '未经学管允许私自更改课程安排',
    description: '未经学管允许私自更改课程安排',
    scoreDelta: -6,
    isEnabled: true,
    sortOrder: 80,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-severe-09',
    category: TutorCreditRuleCategory.SEVERE,
    title: '学生或家长投诉',
    description: '学生或家长投诉',
    scoreDelta: -6,
    isEnabled: true,
    sortOrder: 90,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-severe-10',
    category: TutorCreditRuleCategory.SEVERE,
    title: '招生老师投诉',
    description: '招生老师投诉',
    scoreDelta: -6,
    isEnabled: true,
    sortOrder: 100,
    createdAt: now,
    updatedAt: now,
  },

  // ── 红线行为（扣 12 分 + 立即清退）──
  {
    id: 'tcr-redline-01',
    category: TutorCreditRuleCategory.REDLINE,
    title: '向家长收取额外费用',
    description: '向家长收取交付中心规定以外的额外费用',
    scoreDelta: -12,
    isEnabled: true,
    sortOrder: 10,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-redline-02',
    category: TutorCreditRuleCategory.REDLINE,
    title: '引导家长脱离平台私下带课',
    description: '引导家长脱离平台，私下为学生带课',
    scoreDelta: -12,
    isEnabled: true,
    sortOrder: 20,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-redline-03',
    category: TutorCreditRuleCategory.REDLINE,
    title: '故意泄露学生隐私',
    description: '故意泄露学生隐私',
    scoreDelta: -12,
    isEnabled: true,
    sortOrder: 30,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-redline-04',
    category: TutorCreditRuleCategory.REDLINE,
    title: '侮辱学生/家长/招生老师',
    description: '侮辱学生、家长、招生老师',
    scoreDelta: -12,
    isEnabled: true,
    sortOrder: 40,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-redline-05',
    category: TutorCreditRuleCategory.REDLINE,
    title: '擅自放弃既定课程',
    description: '在教学任务执行过程中，擅自放弃既定课程',
    scoreDelta: -12,
    isEnabled: true,
    sortOrder: 50,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-redline-06',
    category: TutorCreditRuleCategory.REDLINE,
    title: '个人原因引发严重教学事故导致退课',
    description: '因个人原因引发严重教学事故，造成学生退课',
    scoreDelta: -12,
    isEnabled: true,
    sortOrder: 60,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'tcr-redline-07',
    category: TutorCreditRuleCategory.REDLINE,
    title: '遭到家长或招生老师严重投诉',
    description: '遭到家长或招生老师严重的投诉',
    scoreDelta: -12,
    isEnabled: true,
    sortOrder: 70,
    createdAt: now,
    updatedAt: now,
  },
]
