import { TutorCreditLog, TutorCreditChangeType } from '@/types'

export const mockTutorCreditLogs: TutorCreditLog[] = [
  // ━━━ tutor1 (李伴学) — creditScore: 12 ── 10 条记录，中途有扣分后重置回升
  {
    id: 'tcl-tutor1-01',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2022-09-01T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor1-02',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-03',
    ruleName: '课后反馈未在1小时内提交',
    scoreDelta: -1,
    scoreAfter: 11,
    changedAt: new Date('2023-02-14T20:30:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-03',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-04',
    ruleName: '作业批改超过24小时',
    scoreDelta: -1,
    scoreAfter: 10,
    changedAt: new Date('2023-05-08T16:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-04',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-07',
    ruleName: '未提前确认上课时间',
    scoreDelta: -1,
    scoreAfter: 9,
    changedAt: new Date('2023-07-22T10:15:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-05',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-01',
    ruleName: '上课迟到',
    scoreDelta: -3,
    scoreAfter: 6,
    changedAt: new Date('2023-09-10T14:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '上课迟到20分钟，学生家长反映强烈',
  },
  {
    id: 'tcl-tutor1-06',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-02',
    ruleName: '无课堂视频录制文件',
    scoreDelta: -1,
    scoreAfter: 5,
    changedAt: new Date('2023-10-18T11:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-07',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 3,
    scoreAfter: 8,
    changedAt: new Date('2023-12-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '参加专项培训并通过考核，信用分部分恢复',
  },
  {
    id: 'tcl-tutor1-08',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-05',
    ruleName: '学管提醒后8小时内未回复',
    scoreDelta: -1,
    scoreAfter: 7,
    changedAt: new Date('2024-01-15T09:30:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-09',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 3,
    scoreAfter: 10,
    changedAt: new Date('2024-06-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '连续6个月无违规记录，信用分恢复',
  },
  {
    id: 'tcl-tutor1-10',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 2,
    scoreAfter: 12,
    changedAt: new Date('2025-01-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '年度考核优秀，信用分重置为满分',
  },
  {
    id: 'tcl-tutor1-11',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-03',
    ruleName: '课后反馈未在1小时内提交',
    scoreDelta: -1,
    scoreAfter: 11,
    changedAt: new Date('2025-02-05T19:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-12',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-04',
    ruleName: '作业批改超过24小时',
    scoreDelta: -1,
    scoreAfter: 10,
    changedAt: new Date('2025-02-20T15:30:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-13',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-07',
    ruleName: '未提前确认上课时间',
    scoreDelta: -1,
    scoreAfter: 9,
    changedAt: new Date('2025-03-08T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-14',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-02',
    ruleName: '临时申请调课（提前24小时以内）',
    scoreDelta: -3,
    scoreAfter: 6,
    changedAt: new Date('2025-03-22T14:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '临时调课导致学生行程冲突',
  },
  {
    id: 'tcl-tutor1-15',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-02',
    ruleName: '无课堂视频录制文件',
    scoreDelta: -1,
    scoreAfter: 5,
    changedAt: new Date('2025-04-05T11:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-16',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-05',
    ruleName: '学管提醒后8小时内未回复',
    scoreDelta: -1,
    scoreAfter: 4,
    changedAt: new Date('2025-04-18T09:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-17',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 3,
    scoreAfter: 7,
    changedAt: new Date('2025-05-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '参加专项培训并通过考核，信用分部分恢复',
  },
  {
    id: 'tcl-tutor1-18',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-06',
    ruleName: '群内简单问题8小时内未答疑',
    scoreDelta: -1,
    scoreAfter: 6,
    changedAt: new Date('2025-05-15T16:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-19',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-01',
    ruleName: '试听课后未开通数学G账号',
    scoreDelta: -1,
    scoreAfter: 5,
    changedAt: new Date('2025-06-02T14:30:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-20',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 3,
    scoreAfter: 8,
    changedAt: new Date('2025-07-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '连续2个月表现改善，信用分恢复',
  },
  {
    id: 'tcl-tutor1-21',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-03',
    ruleName: '课后反馈未在1小时内提交',
    scoreDelta: -1,
    scoreAfter: 7,
    changedAt: new Date('2025-08-10T20:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-22',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-03',
    ruleName: '未备课直接上课',
    scoreDelta: -3,
    scoreAfter: 4,
    changedAt: new Date('2025-09-15T11:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '学生家长投诉教学内容准备不充分',
  },
  {
    id: 'tcl-tutor1-23',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 2,
    scoreAfter: 6,
    changedAt: new Date('2025-10-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '提交改进方案并通过审核',
  },
  {
    id: 'tcl-tutor1-24',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-04',
    ruleName: '作业批改超过24小时',
    scoreDelta: -1,
    scoreAfter: 5,
    changedAt: new Date('2025-10-20T09:30:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-25',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 3,
    scoreAfter: 8,
    changedAt: new Date('2025-11-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '连续2个月积极整改，信用分恢复',
  },
  {
    id: 'tcl-tutor1-26',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-07',
    ruleName: '未提前确认上课时间',
    scoreDelta: -1,
    scoreAfter: 7,
    changedAt: new Date('2025-11-18T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-27',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 4,
    scoreAfter: 11,
    changedAt: new Date('2025-12-15T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '季度考核优秀，信用分大幅恢复',
  },
  {
    id: 'tcl-tutor1-28',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-05',
    ruleName: '学管提醒后8小时内未回复',
    scoreDelta: -1,
    scoreAfter: 10,
    changedAt: new Date('2026-01-08T09:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-29',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-03',
    ruleName: '课后反馈未在1小时内提交',
    scoreDelta: -1,
    scoreAfter: 9,
    changedAt: new Date('2026-02-12T19:30:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor1-30',
    tutorId: 'user-tutor-1',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 3,
    scoreAfter: 12,
    changedAt: new Date('2026-03-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '连续3个月无严重违规，信用分恢复至满分',
  },

  // ━━━ tutor2 (王金牌) — creditScore: 11 ── 10 条记录
  {
    id: 'tcl-tutor2-01',
    tutorId: 'user-tutor-2',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2022-11-15T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor2-02',
    tutorId: 'user-tutor-2',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-01',
    ruleName: '试听课后未开通数学G账号',
    scoreDelta: -1,
    scoreAfter: 11,
    changedAt: new Date('2023-03-10T14:30:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor2-03',
    tutorId: 'user-tutor-2',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-06',
    ruleName: '群内简单问题8小时内未答疑',
    scoreDelta: -1,
    scoreAfter: 10,
    changedAt: new Date('2023-06-05T16:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor2-04',
    tutorId: 'user-tutor-2',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-10',
    ruleName: '进学生群未修改群名片',
    scoreDelta: -1,
    scoreAfter: 9,
    changedAt: new Date('2023-08-20T11:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor2-05',
    tutorId: 'user-tutor-2',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-08',
    ruleName: '微信头像另类被家长投诉',
    scoreDelta: -1,
    scoreAfter: 8,
    changedAt: new Date('2023-10-12T09:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor2-06',
    tutorId: 'user-tutor-2',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-04',
    ruleName: '12小时内未提交课后反馈',
    scoreDelta: -3,
    scoreAfter: 5,
    changedAt: new Date('2024-01-08T15:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor2-07',
    tutorId: 'user-tutor-2',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 2,
    scoreAfter: 7,
    changedAt: new Date('2024-03-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '积极整改，信用分部分恢复',
  },
  {
    id: 'tcl-tutor2-08',
    tutorId: 'user-tutor-2',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-03',
    ruleName: '课后反馈未在1小时内提交',
    scoreDelta: -1,
    scoreAfter: 6,
    changedAt: new Date('2024-04-15T19:30:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor2-09',
    tutorId: 'user-tutor-2',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 3,
    scoreAfter: 9,
    changedAt: new Date('2024-07-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '连续3个月无违规，信用分恢复',
  },
  {
    id: 'tcl-tutor2-10',
    tutorId: 'user-tutor-2',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 2,
    scoreAfter: 11,
    changedAt: new Date('2025-01-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '年度考核良好，信用分恢复',
  },

  // ━━━ tutor3 (刘资深) — creditScore: 10 ── 10 条记录
  {
    id: 'tcl-tutor3-01',
    tutorId: 'user-tutor-3',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-01-10T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor3-02',
    tutorId: 'user-tutor-3',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-03',
    ruleName: '课后反馈未在1小时内提交',
    scoreDelta: -1,
    scoreAfter: 11,
    changedAt: new Date('2023-04-18T20:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor3-03',
    tutorId: 'user-tutor-3',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-05',
    ruleName: '学管提醒后8小时内未回复',
    scoreDelta: -1,
    scoreAfter: 10,
    changedAt: new Date('2023-06-20T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor3-04',
    tutorId: 'user-tutor-3',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-02',
    ruleName: '临时申请调课（提前24小时以内）',
    scoreDelta: -3,
    scoreAfter: 7,
    changedAt: new Date('2023-09-05T16:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor3-05',
    tutorId: 'user-tutor-3',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-04',
    ruleName: '作业批改超过24小时',
    scoreDelta: -1,
    scoreAfter: 6,
    changedAt: new Date('2023-11-12T11:30:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor3-06',
    tutorId: 'user-tutor-3',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-02',
    ruleName: '无课堂视频录制文件',
    scoreDelta: -1,
    scoreAfter: 5,
    changedAt: new Date('2024-01-18T09:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor3-07',
    tutorId: 'user-tutor-3',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 2,
    scoreAfter: 7,
    changedAt: new Date('2024-03-15T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '积极改进，信用分部分恢复',
  },
  {
    id: 'tcl-tutor3-08',
    tutorId: 'user-tutor-3',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-09',
    ruleName: '微信名另类被家长投诉',
    scoreDelta: -1,
    scoreAfter: 6,
    changedAt: new Date('2024-05-20T14:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor3-09',
    tutorId: 'user-tutor-3',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 3,
    scoreAfter: 9,
    changedAt: new Date('2024-09-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '连续4个月无违规，信用分恢复',
  },
  {
    id: 'tcl-tutor3-10',
    tutorId: 'user-tutor-3',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 1,
    scoreAfter: 10,
    changedAt: new Date('2025-01-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '年度考核合格，信用分恢复',
  },

  // ━━━ tutor4 (陈老师) — creditScore: 10 ── 10 条记录
  {
    id: 'tcl-tutor4-01',
    tutorId: 'user-tutor-4',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-02-20T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor4-02',
    tutorId: 'user-tutor-4',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-07',
    ruleName: '未提前确认上课时间',
    scoreDelta: -1,
    scoreAfter: 11,
    changedAt: new Date('2023-05-15T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor4-03',
    tutorId: 'user-tutor-4',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-03',
    ruleName: '未备课直接上课',
    scoreDelta: -3,
    scoreAfter: 8,
    changedAt: new Date('2023-08-01T11:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor4-04',
    tutorId: 'user-tutor-4',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-01',
    ruleName: '试听课后未开通数学G账号',
    scoreDelta: -1,
    scoreAfter: 7,
    changedAt: new Date('2023-10-10T15:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor4-05',
    tutorId: 'user-tutor-4',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-02',
    ruleName: '无课堂视频录制文件',
    scoreDelta: -1,
    scoreAfter: 6,
    changedAt: new Date('2024-01-15T09:30:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor4-06',
    tutorId: 'user-tutor-4',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 2,
    scoreAfter: 8,
    changedAt: new Date('2024-03-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '经考核表现良好，信用分部分恢复',
  },
  {
    id: 'tcl-tutor4-07',
    tutorId: 'user-tutor-4',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-06',
    ruleName: '群内简单问题8小时内未答疑',
    scoreDelta: -1,
    scoreAfter: 7,
    changedAt: new Date('2024-05-10T14:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor4-08',
    tutorId: 'user-tutor-4',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-05',
    ruleName: '12小时内未批改作业',
    scoreDelta: -3,
    scoreAfter: 4,
    changedAt: new Date('2024-07-20T11:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor4-09',
    tutorId: 'user-tutor-4',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 3,
    scoreAfter: 7,
    changedAt: new Date('2024-10-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '连续3个月表现良好，信用分恢复',
  },
  {
    id: 'tcl-tutor4-10',
    tutorId: 'user-tutor-4',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 3,
    scoreAfter: 10,
    changedAt: new Date('2025-01-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '年度考核优秀，信用分恢复',
  },

  // ━━━ tutor5 (杨老师) — creditScore: 9 ── 5 条记录
  {
    id: 'tcl-tutor5-01',
    tutorId: 'user-tutor-5',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-03-05T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor5-02',
    tutorId: 'user-tutor-5',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-07',
    ruleName: '上课不讲普通话被家长投诉',
    scoreDelta: -3,
    scoreAfter: 9,
    changedAt: new Date('2023-11-20T15:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },

  // ━━━ tutor6 (黄老师) — creditScore: 8 ── 3 条记录
  {
    id: 'tcl-tutor6-01',
    tutorId: 'user-tutor-6',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-04-18T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor6-02',
    tutorId: 'user-tutor-6',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-03',
    ruleName: '课后反馈未在1小时内提交',
    scoreDelta: -1,
    scoreAfter: 11,
    changedAt: new Date('2023-07-10T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor6-03',
    tutorId: 'user-tutor-6',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-06',
    ruleName: '12小时内未完成群内答疑',
    scoreDelta: -3,
    scoreAfter: 8,
    changedAt: new Date('2024-02-05T14:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },

  // ━━━ tutor7 (赵老师) — creditScore: 12 ── 1 条记录（满分无扣分）
  {
    id: 'tcl-tutor7-01',
    tutorId: 'user-tutor-7',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2022-08-01T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },

  // ━━━ tutor8 (周老师) — creditScore: 9 ── 3 条记录
  {
    id: 'tcl-tutor8-01',
    tutorId: 'user-tutor-8',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-01-22T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor8-02',
    tutorId: 'user-tutor-8',
    changeType: TutorCreditChangeType.SEVERE_VIOLATION,
    ruleId: 'tcr-severe-03',
    ruleName: '主动向家长发送个人简历',
    scoreDelta: -6,
    scoreAfter: 6,
    changedAt: new Date('2023-10-15T09:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor8-03',
    tutorId: 'user-tutor-8',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 3,
    scoreAfter: 9,
    changedAt: new Date('2024-04-01T10:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
    note: '完成专项培训，信用分部分恢复',
  },

  // ━━━ tutor9 (吴老师) — creditScore: 7 ── 4 条记录
  {
    id: 'tcl-tutor9-01',
    tutorId: 'user-tutor-9',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-05-30T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor9-02',
    tutorId: 'user-tutor-9',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-01',
    ruleName: '上课迟到',
    scoreDelta: -3,
    scoreAfter: 9,
    changedAt: new Date('2023-09-12T11:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor9-03',
    tutorId: 'user-tutor-9',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-03',
    ruleName: '课后反馈未在1小时内提交',
    scoreDelta: -1,
    scoreAfter: 8,
    changedAt: new Date('2024-01-08T10:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor9-04',
    tutorId: 'user-tutor-9',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-02',
    ruleName: '无课堂视频录制文件',
    scoreDelta: -1,
    scoreAfter: 7,
    changedAt: new Date('2024-03-20T16:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },

  // ━━━ tutor10 (徐老师) — creditScore: 6 ── 2 条记录
  {
    id: 'tcl-tutor10-01',
    tutorId: 'user-tutor-10',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-06-14T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor10-02',
    tutorId: 'user-tutor-10',
    changeType: TutorCreditChangeType.SEVERE_VIOLATION,
    ruleId: 'tcr-severe-02',
    ruleName: '不请假无故缺课',
    scoreDelta: -6,
    scoreAfter: 6,
    changedAt: new Date('2024-02-18T14:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },

  // ━━━ tutor11 (孙老师) — creditScore: 4 ── 5 条记录
  {
    id: 'tcl-tutor11-01',
    tutorId: 'user-tutor-11',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-07-08T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor11-02',
    tutorId: 'user-tutor-11',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-01',
    ruleName: '上课迟到',
    scoreDelta: -3,
    scoreAfter: 9,
    changedAt: new Date('2023-10-05T10:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor11-03',
    tutorId: 'user-tutor-11',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-03',
    ruleName: '未备课直接上课',
    scoreDelta: -3,
    scoreAfter: 6,
    changedAt: new Date('2024-01-22T15:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor11-04',
    tutorId: 'user-tutor-11',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-01',
    ruleName: '试听课后未开通数学G账号',
    scoreDelta: -1,
    scoreAfter: 5,
    changedAt: new Date('2024-03-10T09:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor11-05',
    tutorId: 'user-tutor-11',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-04',
    ruleName: '作业批改超过24小时',
    scoreDelta: -1,
    scoreAfter: 4,
    changedAt: new Date('2024-04-15T11:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },

  // ━━━ tutor12 (马老师) — creditScore: 10 ── 3 条记录
  {
    id: 'tcl-tutor12-01',
    tutorId: 'user-tutor-12',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-02-01T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor12-02',
    tutorId: 'user-tutor-12',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-02',
    ruleName: '临时申请调课（提前24小时以内）',
    scoreDelta: -3,
    scoreAfter: 9,
    changedAt: new Date('2023-12-01T10:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor12-03',
    tutorId: 'user-tutor-12',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 1,
    scoreAfter: 10,
    changedAt: new Date('2024-02-20T10:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
    note: '表现有所改善，信用分回调',
  },

  // ━━━ tutor13 (朱老师) — creditScore: 11 ── 2 条记录
  {
    id: 'tcl-tutor13-01',
    tutorId: 'user-tutor-13',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2022-10-10T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor13-02',
    tutorId: 'user-tutor-13',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-03',
    ruleName: '课后反馈未在1小时内提交',
    scoreDelta: -1,
    scoreAfter: 11,
    changedAt: new Date('2023-05-18T14:00:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
  },

  // ━━━ tutor14 (胡老师) — creditScore: 9 ── 2 条记录
  {
    id: 'tcl-tutor14-01',
    tutorId: 'user-tutor-14',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-03-25T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor14-02',
    tutorId: 'user-tutor-14',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-01',
    ruleName: '上课迟到',
    scoreDelta: -3,
    scoreAfter: 9,
    changedAt: new Date('2024-01-30T10:00:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
  },

  // ━━━ tutor15 ~ tutor20 简要记录（只有初始注册）
  {
    id: 'tcl-tutor15-01',
    tutorId: 'user-tutor-15',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-08-01T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor15-02',
    tutorId: 'user-tutor-15',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-06',
    ruleName: '12小时内未完成群内答疑',
    scoreDelta: -3,
    scoreAfter: 9,
    changedAt: new Date('2024-03-15T10:00:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
  },
  {
    id: 'tcl-tutor15-03',
    tutorId: 'user-tutor-15',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-04',
    ruleName: '作业批改超过24小时',
    scoreDelta: -1,
    scoreAfter: 8,
    changedAt: new Date('2024-06-20T14:00:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
  },
  {
    id: 'tcl-tutor15-04',
    tutorId: 'user-tutor-15',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: -1,
    scoreAfter: 7,
    changedAt: new Date('2024-08-01T09:00:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
    note: '注：此处为补录扣分记录',
  },

  {
    id: 'tcl-tutor16-01',
    tutorId: 'user-tutor-16',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-09-12T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor16-02',
    tutorId: 'user-tutor-16',
    changeType: TutorCreditChangeType.SEVERE_VIOLATION,
    ruleId: 'tcr-severe-09',
    ruleName: '学生或家长投诉',
    scoreDelta: -6,
    scoreAfter: 6,
    changedAt: new Date('2024-01-10T14:00:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
  },
  {
    id: 'tcl-tutor16-03',
    tutorId: 'user-tutor-16',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-04',
    ruleName: '12小时内未提交课后反馈',
    scoreDelta: -3,
    scoreAfter: 3,
    changedAt: new Date('2024-04-08T10:00:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
  },

  {
    id: 'tcl-tutor17-01',
    tutorId: 'user-tutor-17',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-10-05T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor17-02',
    tutorId: 'user-tutor-17',
    changeType: TutorCreditChangeType.SEVERE_VIOLATION,
    ruleId: 'tcr-severe-01',
    ruleName: '临时取消课程',
    scoreDelta: -6,
    scoreAfter: 6,
    changedAt: new Date('2024-01-20T16:00:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
  },
  {
    id: 'tcl-tutor17-03',
    tutorId: 'user-tutor-17',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-03',
    ruleName: '未备课直接上课',
    scoreDelta: -3,
    scoreAfter: 3,
    changedAt: new Date('2024-03-05T11:00:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
  },
  {
    id: 'tcl-tutor17-04',
    tutorId: 'user-tutor-17',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-05',
    ruleName: '12小时内未批改作业',
    scoreDelta: -3,
    scoreAfter: 1,
    changedAt: new Date('2024-05-18T09:30:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
    note: '已接近清退线，给予最后警告',
  },

  {
    id: 'tcl-tutor18-01',
    tutorId: 'user-tutor-18',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-04-01T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor18-02',
    tutorId: 'user-tutor-18',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'tcr-minor-07',
    ruleName: '未提前确认上课时间',
    scoreDelta: -1,
    scoreAfter: 11,
    changedAt: new Date('2024-01-20T10:00:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
  },
  {
    id: 'tcl-tutor18-03',
    tutorId: 'user-tutor-18',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-01',
    ruleName: '上课迟到',
    scoreDelta: -3,
    scoreAfter: 8,
    changedAt: new Date('2024-06-10T14:00:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
  },

  {
    id: 'tcl-tutor19-01',
    tutorId: 'user-tutor-19',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-11-20T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor19-02',
    tutorId: 'user-tutor-19',
    changeType: TutorCreditChangeType.SEVERE_VIOLATION,
    ruleId: 'tcr-severe-08',
    ruleName: '未经学管允许私自更改课程安排',
    scoreDelta: -6,
    scoreAfter: 6,
    changedAt: new Date('2024-04-10T15:00:00'),
    submittedById: 'user-manager-0',
    submittedByName: '陈总监',
  },

  {
    id: 'tcl-tutor20-01',
    tutorId: 'user-tutor-20',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-12-01T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor20-02',
    tutorId: 'user-tutor-20',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'tcr-general-04',
    ruleName: '12小时内未提交课后反馈',
    scoreDelta: -3,
    scoreAfter: 9,
    changedAt: new Date('2024-05-22T11:00:00'),
    submittedById: 'user-manager-0',
    submittedByName: '陈总监',
  },
]
