import { TutorCreditLog, TutorCreditChangeType } from '@/types'

// Each tutor starts with 12 points at registration.
// Some tutors have deductions recorded to show realistic history.
// Data is sorted newest-first per tutor, but the array is mixed — pages will sort on load.

export const mockTutorCreditLogs: TutorCreditLog[] = [
  // ── tutor1 (李伴学) — creditScore: 12, no deductions ──
  {
    id: 'tcl-tutor1-1',
    tutorId: 'tutor1',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2022-09-01T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },

  // ── tutor2 (王金牌) — creditScore: 11, one minor deduction ──
  {
    id: 'tcl-tutor2-1',
    tutorId: 'tutor2',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2022-11-15T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor2-2',
    tutorId: 'tutor2',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'rule-minor-1',
    ruleName: '上课迟到（5-15分钟）',
    scoreDelta: -1,
    scoreAfter: 11,
    changedAt: new Date('2023-04-10T14:30:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },

  // ── tutor3 (刘资深) — creditScore: 10, two deductions ──
  {
    id: 'tcl-tutor3-1',
    tutorId: 'tutor3',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-01-10T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor3-2',
    tutorId: 'tutor3',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'rule-minor-3',
    ruleName: '未按要求填写课后反馈',
    scoreDelta: -1,
    scoreAfter: 11,
    changedAt: new Date('2023-06-20T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor3-3',
    tutorId: 'tutor3',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'rule-minor-2',
    ruleName: '无故取消课程（提前24小时内）',
    scoreDelta: -1,
    scoreAfter: 10,
    changedAt: new Date('2023-09-05T16:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },

  // ── tutor4 (陈老师) — creditScore: 10 ──
  {
    id: 'tcl-tutor4-1',
    tutorId: 'tutor4',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-02-20T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor4-2',
    tutorId: 'tutor4',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'rule-general-1',
    ruleName: '私下与家长收费',
    scoreDelta: -3,
    scoreAfter: 9,
    changedAt: new Date('2023-08-01T11:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor4-3',
    tutorId: 'tutor4',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'rule-minor-4',
    ruleName: '上课环境嘈杂',
    scoreDelta: -1,
    scoreAfter: 8,
    changedAt: new Date('2024-01-15T09:30:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor4-4',
    tutorId: 'tutor4',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 2,
    scoreAfter: 10,
    changedAt: new Date('2024-03-01T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
    note: '经考核表现良好，重置信用分',
  },

  // ── tutor5 (杨老师) — creditScore: 9 ──
  {
    id: 'tcl-tutor5-1',
    tutorId: 'tutor5',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-03-05T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor5-2',
    tutorId: 'tutor5',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'rule-general-2',
    ruleName: '对学员态度恶劣',
    scoreDelta: -3,
    scoreAfter: 9,
    changedAt: new Date('2023-11-20T15:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },

  // ── tutor6 (黄老师) — creditScore: 8 ──
  {
    id: 'tcl-tutor6-1',
    tutorId: 'tutor6',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-04-18T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor6-2',
    tutorId: 'tutor6',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'rule-minor-1',
    ruleName: '上课迟到（5-15分钟）',
    scoreDelta: -1,
    scoreAfter: 11,
    changedAt: new Date('2023-07-10T10:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },
  {
    id: 'tcl-tutor6-3',
    tutorId: 'tutor6',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'rule-general-3',
    ruleName: '课程质量严重不达标',
    scoreDelta: -3,
    scoreAfter: 8,
    changedAt: new Date('2024-02-05T14:00:00'),
    submittedById: 'user-manager-1',
    submittedByName: '王学管',
  },

  // ── tutor7 (赵老师) — creditScore: 12 ──
  {
    id: 'tcl-tutor7-1',
    tutorId: 'tutor7',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2022-08-01T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },

  // ── tutor8 (周老师) — creditScore: 9 ──
  {
    id: 'tcl-tutor8-1',
    tutorId: 'tutor8',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-01-22T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor8-2',
    tutorId: 'tutor8',
    changeType: TutorCreditChangeType.SEVERE_VIOLATION,
    ruleId: 'rule-severe-1',
    ruleName: '泄露学员个人信息',
    scoreDelta: -6,
    scoreAfter: 6,
    changedAt: new Date('2023-10-15T09:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor8-3',
    tutorId: 'tutor8',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 3,
    scoreAfter: 9,
    changedAt: new Date('2024-04-01T10:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
    note: '完成专项培训，重置信用分至9分',
  },

  // ── tutor9 (吴老师) — creditScore: 7 ──
  {
    id: 'tcl-tutor9-1',
    tutorId: 'tutor9',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-05-30T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor9-2',
    tutorId: 'tutor9',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'rule-general-1',
    ruleName: '私下与家长收费',
    scoreDelta: -3,
    scoreAfter: 9,
    changedAt: new Date('2023-09-12T11:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor9-3',
    tutorId: 'tutor9',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'rule-minor-3',
    ruleName: '未按要求填写课后反馈',
    scoreDelta: -1,
    scoreAfter: 8,
    changedAt: new Date('2024-01-08T10:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor9-4',
    tutorId: 'tutor9',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'rule-minor-2',
    ruleName: '无故取消课程（提前24小时内）',
    scoreDelta: -1,
    scoreAfter: 7,
    changedAt: new Date('2024-03-20T16:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },

  // ── tutor10 (徐老师) — creditScore: 6 ──
  {
    id: 'tcl-tutor10-1',
    tutorId: 'tutor10',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-06-14T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor10-2',
    tutorId: 'tutor10',
    changeType: TutorCreditChangeType.SEVERE_VIOLATION,
    ruleId: 'rule-severe-2',
    ruleName: '拒绝配合平台检查',
    scoreDelta: -6,
    scoreAfter: 6,
    changedAt: new Date('2024-02-18T14:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },

  // ── tutor11 (孙老师) — creditScore: 4 ──
  {
    id: 'tcl-tutor11-1',
    tutorId: 'tutor11',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-07-08T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor11-2',
    tutorId: 'tutor11',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'rule-general-2',
    ruleName: '对学员态度恶劣',
    scoreDelta: -3,
    scoreAfter: 9,
    changedAt: new Date('2023-10-05T10:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor11-3',
    tutorId: 'tutor11',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'rule-general-3',
    ruleName: '课程质量严重不达标',
    scoreDelta: -3,
    scoreAfter: 6,
    changedAt: new Date('2024-01-22T15:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor11-4',
    tutorId: 'tutor11',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'rule-minor-1',
    ruleName: '上课迟到（5-15分钟）',
    scoreDelta: -1,
    scoreAfter: 5,
    changedAt: new Date('2024-03-10T09:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor11-5',
    tutorId: 'tutor11',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'rule-minor-5',
    ruleName: '未提前通知调课',
    scoreDelta: -1,
    scoreAfter: 4,
    changedAt: new Date('2024-04-15T11:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },

  // ── tutor12 (马老师) — creditScore: 10 ──
  {
    id: 'tcl-tutor12-1',
    tutorId: 'tutor12',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-02-01T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor12-2',
    tutorId: 'tutor12',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'rule-general-1',
    ruleName: '私下与家长收费',
    scoreDelta: -3,
    scoreAfter: 9,
    changedAt: new Date('2023-12-01T10:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
  },
  {
    id: 'tcl-tutor12-3',
    tutorId: 'tutor12',
    changeType: TutorCreditChangeType.RESET,
    scoreDelta: 1,
    scoreAfter: 10,
    changedAt: new Date('2024-02-20T10:00:00'),
    submittedById: 'user-manager-2',
    submittedByName: '李学管',
    note: '表现有所改善，信用分回调',
  },

  // ── tutor13 (朱老师) — creditScore: 11 ──
  {
    id: 'tcl-tutor13-1',
    tutorId: 'tutor13',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2022-10-10T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor13-2',
    tutorId: 'tutor13',
    changeType: TutorCreditChangeType.MINOR_VIOLATION,
    ruleId: 'rule-minor-3',
    ruleName: '未按要求填写课后反馈',
    scoreDelta: -1,
    scoreAfter: 11,
    changedAt: new Date('2023-05-18T14:00:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
  },

  // ── tutor14 (胡老师) — creditScore: 9 ──
  {
    id: 'tcl-tutor14-1',
    tutorId: 'tutor14',
    changeType: TutorCreditChangeType.INITIAL_REGISTRATION,
    scoreDelta: 12,
    scoreAfter: 12,
    changedAt: new Date('2023-03-25T09:00:00'),
    submittedById: 'system',
    submittedByName: '系统',
  },
  {
    id: 'tcl-tutor14-2',
    tutorId: 'tutor14',
    changeType: TutorCreditChangeType.GENERAL_VIOLATION,
    ruleId: 'rule-general-2',
    ruleName: '对学员态度恶劣',
    scoreDelta: -3,
    scoreAfter: 9,
    changedAt: new Date('2024-01-30T10:00:00'),
    submittedById: 'user-manager-3',
    submittedByName: '张学管',
  },
]
