import { OrderStatus, OrderType, Role, type StudentProfile, type WorkbenchTask, type WorkbenchTaskType } from '@/types'

export const mockWorkbenchTaskTypes: WorkbenchTaskType[] = [
  {
    id: 'task-type-trial-prep',
    name: '试课备课',
    description: '教练在试课前提交备课要点、课堂目标与预计提分路径。',
    applicableRoles: [Role.TUTOR],
    detectorId: 'trialPrep',
    detectorConfig: {
      orderTypes: [OrderType.TRIAL],
      orderStatuses: [OrderStatus.ASSIGNED, OrderStatus.IN_PROGRESS],
      preStartHours: 72,
      postEndHours: 2,
      ownerField: 'assignedTeacherId',
      dueOffsetHours: -1,
    },
    completionConfig: {
      requireSubmission: true,
      submittedOnly: true,
      requiredFields: ['diagnosisNotes', 'teachingGoals'],
      requireAttachmentOrText: true,
      allowDraft: false,
    },
    actionHrefTemplate: '/trial-prep/{orderId}',
    defaultDeadlineHours: 6,
    defaultPriority: 'HIGH',
    countsTowardAssessment: true,
    parentVisible: false,
    enabled: true,
    sortOrder: 1,
    createdAt: new Date('2026-06-01'),
    updatedAt: new Date('2026-06-01'),
  },
  {
    id: 'task-type-feedback',
    name: '提交课后反馈',
    description: '课后反馈是教师活跃度统计口径，也是家长端成长足迹的数据来源。',
    applicableRoles: [Role.TUTOR],
    detectorId: 'lessonFeedback',
    detectorConfig: {
      orderTypes: [OrderType.TRIAL, OrderType.REGULAR],
      orderStatuses: [OrderStatus.COMPLETED, OrderStatus.IN_PROGRESS],
      ownerField: 'assignedTeacherId',
      postEndHours: 24,
      dueOffsetHours: 24,
    },
    completionConfig: {
      requireSubmission: true,
      submittedOnly: true,
      requiredFields: ['content', 'performance'],
      allowDraft: false,
    },
    actionHrefTemplate: '/my-students/feedback/{orderId}/create',
    defaultDeadlineHours: 24,
    defaultPriority: 'HIGH',
    countsTowardAssessment: true,
    parentVisible: true,
    enabled: true,
    sortOrder: 2,
    createdAt: new Date('2026-06-01'),
    updatedAt: new Date('2026-06-01'),
  },
  {
    id: 'task-type-homework',
    name: '布置作业',
    description: '记录课后作业安排、完成要求和下次课检查点。',
    applicableRoles: [Role.TUTOR],
    detectorId: 'homework',
    detectorConfig: {
      orderTypes: [OrderType.TRIAL, OrderType.REGULAR],
      orderStatuses: [OrderStatus.IN_PROGRESS, OrderStatus.COMPLETED],
      ownerField: 'assignedTeacherId',
      dueOffsetHours: 12,
    },
    completionConfig: {
      requireSubmission: true,
      requiredFields: ['homework'],
      allowDraft: false,
    },
    actionHrefTemplate: '/my-students/feedback/{orderId}/create',
    defaultDeadlineHours: 12,
    defaultPriority: 'MEDIUM',
    countsTowardAssessment: true,
    parentVisible: true,
    enabled: true,
    sortOrder: 3,
    createdAt: new Date('2026-06-01'),
    updatedAt: new Date('2026-06-01'),
  },
  {
    id: 'task-type-trial-follow',
    name: '试课跟进',
    description: '招生老师结合试课反馈与家长沟通，推进转化或复盘未成交原因。',
    applicableRoles: [Role.SALES],
    detectorId: 'trialFollow',
    detectorConfig: {
      orderTypes: [OrderType.TRIAL],
      orderStatuses: [OrderStatus.COMPLETED],
      ownerField: 'salesPersonId',
      dueOffsetHours: 12,
    },
    completionConfig: {
      requireSubmission: true,
      submittedOnly: true,
      allowDraft: false,
    },
    actionHrefTemplate: '/orders/{orderId}',
    defaultDeadlineHours: 12,
    defaultPriority: 'HIGH',
    countsTowardAssessment: true,
    parentVisible: false,
    enabled: true,
    sortOrder: 4,
    createdAt: new Date('2026-06-01'),
    updatedAt: new Date('2026-06-01'),
  },
  {
    id: 'task-type-renewal',
    name: '续费跟进',
    description: '跟进剩余课时较低且近期反馈积极的学生，形成续费沟通记录。',
    applicableRoles: [Role.SALES, Role.MANAGER],
    detectorId: 'renewal',
    detectorConfig: {
      orderTypes: [OrderType.REGULAR],
      orderStatuses: [OrderStatus.IN_PROGRESS, OrderStatus.ASSIGNED],
      ownerField: 'salesPersonId',
      maxRemainingHours: 5,
      dueOffsetHours: 48,
    },
    completionConfig: {
      requireSubmission: true,
      allowDraft: false,
    },
    actionHrefTemplate: '/orders/{orderId}',
    defaultDeadlineHours: 48,
    defaultPriority: 'MEDIUM',
    countsTowardAssessment: true,
    parentVisible: false,
    enabled: true,
    sortOrder: 5,
    createdAt: new Date('2026-06-01'),
    updatedAt: new Date('2026-06-01'),
  },
  {
    id: 'task-type-hours-warning',
    name: '课时预警',
    description: '学管处理剩余课时、冻结课时或消课异常，避免服务中断。',
    applicableRoles: [Role.MANAGER],
    detectorId: 'hoursWarning',
    detectorConfig: {
      orderTypes: [OrderType.REGULAR],
      orderStatuses: [OrderStatus.IN_PROGRESS, OrderStatus.ASSIGNED],
      ownerField: 'managerId',
      maxRemainingHours: 5,
      dueOffsetHours: 24,
    },
    completionConfig: {
      requireSubmission: true,
      allowDraft: false,
    },
    actionHrefTemplate: '/manager-order-search',
    defaultDeadlineHours: 24,
    defaultPriority: 'HIGH',
    countsTowardAssessment: true,
    parentVisible: false,
    enabled: true,
    sortOrder: 6,
    createdAt: new Date('2026-06-01'),
    updatedAt: new Date('2026-06-01'),
  },
  {
    id: 'task-type-complaint',
    name: '家长投诉处理',
    description: '学管或运营处理投诉、升级事项与满意度回访。',
    applicableRoles: [Role.MANAGER, Role.OPERATOR],
    detectorId: 'complaint',
    detectorConfig: {
      orderTypes: [OrderType.TRIAL, OrderType.REGULAR],
      orderStatuses: [OrderStatus.IN_PROGRESS, OrderStatus.COMPLETED],
      ownerField: 'managerId',
      dueOffsetHours: 8,
    },
    completionConfig: {
      requireSubmission: true,
      allowDraft: false,
    },
    actionHrefTemplate: '/teaching-feedback/feedback-search',
    defaultDeadlineHours: 8,
    defaultPriority: 'HIGH',
    countsTowardAssessment: true,
    parentVisible: false,
    enabled: true,
    sortOrder: 7,
    createdAt: new Date('2026-06-01'),
    updatedAt: new Date('2026-06-01'),
  },
  {
    id: 'task-type-income-audit',
    name: '课时费审核',
    description: '运营/财务审核课时费、对账确认与发放异常。',
    applicableRoles: [Role.OPERATOR],
    detectorId: 'incomeAudit',
    detectorConfig: {
      dueOffsetHours: 24,
    },
    completionConfig: {
      requireSubmission: true,
      submittedOnly: true,
      allowDraft: false,
    },
    actionHrefTemplate: '/financial-records',
    defaultDeadlineHours: 24,
    defaultPriority: 'HIGH',
    countsTowardAssessment: true,
    parentVisible: false,
    enabled: true,
    sortOrder: 8,
    createdAt: new Date('2026-06-01'),
    updatedAt: new Date('2026-06-01'),
  },
]

export const mockWorkbenchTasks: WorkbenchTask[] = [
  {
    id: 'wb-sales-1',
    taskTypeId: 'task-type-trial-follow',
    ownerRole: Role.SALES,
    ownerUserId: 'user-sales-1',
    studentId: 'stu-feedback-t-a',
    studentName: '周一诺',
    orderId: 'order-trial-feedback-a',
    title: '试课反馈已回传，需联系家长确认转正意向',
    description: '教练反馈孩子计算准确率提升明显，建议今晚 20:00 前完成沟通。',
    status: 'TODO',
    priority: 'HIGH',
    dueAt: new Date('2026-06-14T20:00:00+08:00'),
    progress: 20,
    actionLabel: '标记已跟进',
    metricLabel: '预计转化 85%',
    createdAt: new Date('2026-06-14T09:00:00+08:00'),
    updatedAt: new Date('2026-06-14T09:00:00+08:00'),
  },
  {
    id: 'wb-sales-2',
    taskTypeId: 'task-type-renewal',
    ownerRole: Role.SALES,
    ownerUserId: 'user-sales-1',
    studentId: 'stu-2',
    studentName: '林小华',
    title: '剩余 4 课时，结合阶段报告做续费沟通',
    description: '近三次作业完成稳定，学管建议本周内推进续费。',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    dueAt: new Date('2026-06-15T18:00:00+08:00'),
    progress: 60,
    actionLabel: '记录沟通结果',
    metricLabel: '剩余 4h',
    createdAt: new Date('2026-06-13T10:00:00+08:00'),
    updatedAt: new Date('2026-06-14T11:00:00+08:00'),
  },
  {
    id: 'wb-tutor-1',
    taskTypeId: 'task-type-trial-prep',
    ownerRole: Role.TUTOR,
    ownerUserId: 'user-tutor-1',
    studentId: 'stu-feedback-t-a',
    studentName: '周一诺',
    orderId: 'order-trial-feedback-a',
    title: '19:30 试课前提交备课准备',
    description: '需包含诊断题、课堂目标、试课后规划建议。',
    status: 'TODO',
    priority: 'HIGH',
    dueAt: new Date('2026-06-14T18:30:00+08:00'),
    progress: 10,
    actionLabel: '提交备课',
    metricLabel: '试课前必做',
    createdAt: new Date('2026-06-14T08:30:00+08:00'),
    updatedAt: new Date('2026-06-14T08:30:00+08:00'),
  },
  {
    id: 'wb-tutor-2',
    taskTypeId: 'task-type-feedback',
    ownerRole: Role.TUTOR,
    ownerUserId: 'user-tutor-1',
    studentId: 'stu-feedback-t-b',
    studentName: '周子墨',
    title: '补交昨日课后反馈',
    description: '反馈提交后才计入教师活跃度，请补充课堂表现与下次课重点。',
    status: 'OVERDUE',
    priority: 'HIGH',
    dueAt: new Date('2026-06-13T22:00:00+08:00'),
    progress: 0,
    actionLabel: '提交反馈',
    metricLabel: '已超时',
    createdAt: new Date('2026-06-13T09:00:00+08:00'),
    updatedAt: new Date('2026-06-14T09:00:00+08:00'),
  },
  {
    id: 'wb-tutor-3',
    taskTypeId: 'task-type-homework',
    ownerRole: Role.TUTOR,
    ownerUserId: 'user-tutor-1',
    studentId: 'stu-feedback-t-c',
    studentName: '周语桐',
    title: '布置分数应用题专项作业',
    description: '家长端可见，建议给出 3 道基础题和 2 道提升题。',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    dueAt: new Date('2026-06-14T23:00:00+08:00'),
    progress: 50,
    actionLabel: '完成作业布置',
    metricLabel: '家长可见',
    createdAt: new Date('2026-06-14T12:00:00+08:00'),
    updatedAt: new Date('2026-06-14T12:00:00+08:00'),
  },
  {
    id: 'wb-manager-1',
    taskTypeId: 'task-type-hours-warning',
    ownerRole: Role.MANAGER,
    ownerUserId: 'user-manager-1',
    studentId: 'stu-2',
    studentName: '林小华',
    title: '课时剩余不足 5h，需安排续费/停课预案',
    description: '当前剩余 4h，招生已开始续费沟通，需学管确认排课节奏。',
    status: 'TODO',
    priority: 'HIGH',
    dueAt: new Date('2026-06-14T21:00:00+08:00'),
    progress: 25,
    actionLabel: '标记已处理',
    metricLabel: '剩余 4h',
    createdAt: new Date('2026-06-14T09:10:00+08:00'),
    updatedAt: new Date('2026-06-14T09:10:00+08:00'),
  },
  {
    id: 'wb-manager-2',
    taskTypeId: 'task-type-complaint',
    ownerRole: Role.MANAGER,
    ownerUserId: 'user-manager-1',
    studentId: 'stu-feedback-t-b',
    studentName: '周子墨',
    title: '家长反馈昨日课堂目标不清晰',
    description: '需复盘教练课后反馈并在 8 小时内回访家长。',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueAt: new Date('2026-06-14T17:30:00+08:00'),
    progress: 45,
    actionLabel: '完成回访',
    metricLabel: '投诉处理',
    createdAt: new Date('2026-06-14T09:30:00+08:00'),
    updatedAt: new Date('2026-06-14T13:00:00+08:00'),
  },
  {
    id: 'wb-manager-3',
    taskTypeId: 'task-type-feedback',
    ownerRole: Role.MANAGER,
    ownerUserId: 'user-manager-1',
    studentId: 'stu-feedback-t-b',
    studentName: '周子墨',
    title: '督促李伴学补交课后反馈',
    description: '该反馈影响教练活跃度，本周团队反馈提交率已低于目标。',
    status: 'OVERDUE',
    priority: 'HIGH',
    dueAt: new Date('2026-06-14T10:00:00+08:00'),
    progress: 0,
    actionLabel: '指派处理',
    metricLabel: '活跃度口径',
    createdAt: new Date('2026-06-14T08:00:00+08:00'),
    updatedAt: new Date('2026-06-14T10:10:00+08:00'),
  },
  {
    id: 'wb-operator-1',
    taskTypeId: 'task-type-income-audit',
    ownerRole: Role.OPERATOR,
    ownerUserId: 'user-operator-1',
    studentName: '华北交付中心',
    title: '审核 12 条课时费异常',
    description: '包含 2 条课时单价异常、3 条未确认消课、7 条待发放记录。',
    status: 'TODO',
    priority: 'HIGH',
    dueAt: new Date('2026-06-14T19:00:00+08:00'),
    progress: 15,
    actionLabel: '模拟审核通过',
    metricLabel: '12 条',
    createdAt: new Date('2026-06-14T09:00:00+08:00'),
    updatedAt: new Date('2026-06-14T09:00:00+08:00'),
  },
  {
    id: 'wb-operator-2',
    taskTypeId: 'task-type-complaint',
    ownerRole: Role.OPERATOR,
    ownerUserId: 'user-operator-1',
    studentId: 'stu-feedback-t-b',
    studentName: '周子墨',
    title: '学管升级：家长投诉需运营介入',
    description: '学管已初步回访，家长要求运营确认后续服务保障。',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueAt: new Date('2026-06-14T18:00:00+08:00'),
    progress: 40,
    actionLabel: '完成升级处理',
    metricLabel: '升级事项',
    escalationFrom: '王学管',
    createdAt: new Date('2026-06-14T11:00:00+08:00'),
    updatedAt: new Date('2026-06-14T13:00:00+08:00'),
  },
  {
    id: 'wb-operator-3',
    taskTypeId: 'task-type-income-audit',
    ownerRole: Role.OPERATOR,
    ownerUserId: 'user-operator-1',
    title: '对账确认：华北交付中心 6 月第二周',
    description: '需确认消课执行、课时费金额与财务发放批次一致。',
    status: 'OVERDUE',
    priority: 'HIGH',
    dueAt: new Date('2026-06-13T20:00:00+08:00'),
    progress: 30,
    actionLabel: '完成对账',
    metricLabel: '已超时',
    createdAt: new Date('2026-06-13T09:00:00+08:00'),
    updatedAt: new Date('2026-06-14T09:00:00+08:00'),
  },
]

export const mockStudentProfiles: StudentProfile[] = [
  {
    id: 'profile-stu-feedback-t-a',
    studentId: 'stu-feedback-t-a',
    abilityProfile: '计算基础扎实，应用题审题速度偏慢，适合用分层题单逐步提升。',
    personality: '课堂回应积极，遇到难题会先尝试表达思路，需要正向鼓励。',
    homeworkHabit: '作业提交及时，但订正说明偏简略，需要强化错因归纳。',
    learningPlan: '未来 4 周围绕分数应用题、行程问题和错题复盘建立稳定解题流程。',
    parentSummary: '本周重点是让孩子把“会做”转化为“讲得清楚”，家长可关注订正质量。',
    growthScore: 86,
    visibleToParent: true,
    timeline: [
      {
        id: 'timeline-a-1',
        type: 'PLAN',
        title: '四周学习规划已生成',
        summary: '第 1 周查漏补缺，第 2-3 周专项突破，第 4 周做阶段测评。',
        date: new Date('2026-06-10'),
        parentVisible: true,
      },
      {
        id: 'timeline-a-2',
        type: 'FEEDBACK',
        title: '试课反馈：计算正确率提升',
        summary: '课堂中能独立完成基础题，应用题需要继续训练关键词提取。',
        date: new Date('2026-06-12'),
        parentVisible: true,
      },
      {
        id: 'timeline-a-3',
        type: 'HOMEWORK',
        title: '分数应用题专项作业',
        summary: '完成 5 道基础题和 2 道提升题，下次课检查错因归纳。',
        date: new Date('2026-06-14'),
        parentVisible: true,
      },
    ],
    createdAt: new Date('2026-06-10'),
    updatedAt: new Date('2026-06-14'),
  },
  {
    id: 'profile-stu-feedback-t-b',
    studentId: 'stu-feedback-t-b',
    abilityProfile: '函数基础较弱，但图像理解能力好，适合从可视化题型切入。',
    personality: '对成绩波动敏感，课堂上需要明确阶段目标和即时反馈。',
    homeworkHabit: '作业完成率 78%，周末容易延迟提交，需要家长提醒固定时段。',
    learningPlan: '两周内补齐一次函数基础概念，再进入综合题训练。',
    parentSummary: '建议家长只关注完成时间和错题订正，不额外增加题量。',
    growthScore: 74,
    visibleToParent: true,
    timeline: [
      {
        id: 'timeline-b-1',
        type: 'REPORT',
        title: '阶段提升报告',
        summary: '近 3 次测评从 68 分提升到 76 分，主要提升来自基础题稳定性。',
        date: new Date('2026-06-08'),
        parentVisible: true,
      },
      {
        id: 'timeline-b-2',
        type: 'FEEDBACK',
        title: '课堂反馈待补全',
        summary: '反馈尚未提交，提交后将同步到成长足迹。',
        date: new Date('2026-06-13'),
        parentVisible: false,
      },
    ],
    createdAt: new Date('2026-06-08'),
    updatedAt: new Date('2026-06-14'),
  },
]
