
export const STUDENTS_MOCK = [
  {
    id: "STU-2024001",
    name: "张小明",
    gender: "男",
    grade: "初二",
    subject: "数学",
    parentPhone: "13800138000",
    region: "北京市海淀区",
    school: "人大附中",
    status: "regular", // regular, trial, graduated
    enrollmentDate: "2024-02-01",
    parentName: "张先生",
    parentRelation: "father",
    campusName: "北京校区",
    campusAccount: "beijing_01",
    studentAccount: "stu_001",
  },
  {
    id: "STU-2024002",
    name: "李小红",
    gender: "女",
    grade: "高一",
    subject: "英语",
    parentPhone: "13900139000",
    region: "上海市浦东新区",
    school: "建平中学",
    status: "trial",
    enrollmentDate: "2024-02-03",
    parentName: "李女士",
    parentRelation: "mother",
    campusName: "上海校区",
    campusAccount: "shanghai_01",
    studentAccount: "stu_002",
  },
  {
    id: "STU-2024003",
    name: "王大力",
    gender: "男",
    grade: "初三",
    subject: "物理",
    parentPhone: "13700137000",
    region: "广州市天河区",
    school: "华师附中",
    status: "regular",
    enrollmentDate: "2024-01-15",
    parentName: "王先生",
    parentRelation: "father",
    campusName: "广州校区",
    campusAccount: "guangzhou_01",
    studentAccount: "stu_003",
  },
  {
    id: "STU-2024004",
    name: "赵敏",
    gender: "女",
    grade: "高三",
    subject: "化学",
    parentPhone: "13600136000",
    region: "深圳市南山区",
    school: "深圳中学",
    status: "graduated",
    enrollmentDate: "2023-09-01",
    parentName: "赵先生",
    parentRelation: "father",
    campusName: "深圳校区",
    campusAccount: "shenzhen_01",
    studentAccount: "stu_004",
  },
  {
    id: "STU-2024005",
    name: "陈思思",
    gender: "女",
    grade: "四年级",
    subject: "英语",
    parentPhone: "13500135000",
    region: "杭州市西湖区",
    school: "学军小学",
    status: "trial",
    enrollmentDate: "2024-02-05",
    parentName: "陈女士",
    parentRelation: "mother",
    campusName: "杭州校区",
    campusAccount: "hangzhou_01",
    studentAccount: "stu_005",
  },
]
